import { ROLE_PACKS } from "./rolePacks";
import type {
  NodeCategory,
  PermissionSet,
  PortDefinition,
  ProviderConfig,
  RolePrompt,
} from "./types";

export interface NodeDefinition {
  id: string;
  title: string;
  category: NodeCategory;
  group?: string;
  icon: string;
  description: string;
  inputs: PortDefinition[];
  outputs: PortDefinition[];
  defaultPurpose?: string;
  configSchema?: {
    key: string;
    label: string;
    type: "text" | "textarea" | "number" | "boolean" | "select";
    options?: string[];
    default?: unknown;
  }[];
  providers?: ProviderConfig[];
  rolePrompt?: RolePrompt;
  requiredPermissions?: string[];
  permissions?: Partial<PermissionSet>;
  contractTimeoutMs?: number;
  feedbackLoopDefault?: "ON" | "OFF";
  evolutionModeDefault?: "OFF" | "SUGGEST" | "AUTONOMOUS";
}

const p = (
  id: string,
  label: string,
  dataType: PortDefinition["dataType"],
  opts: Partial<PortDefinition> = {},
): PortDefinition => ({
  id,
  label,
  direction: "input",
  dataType,
  required: false,
  multiple: false,
  ...opts,
});

const inP = (port: PortDefinition): PortDefinition => ({ ...port, direction: "input" });
const outP = (port: PortDefinition): PortDefinition => ({ ...port, direction: "output" });

const rp = (s: RolePrompt["sections"]): RolePrompt => ({ sections: s, version: 1 });

const stdLearning = (focus: string) =>
  `When feedback is ON, treat every run as a training example. Record reusable procedures as skills, durable facts as memory, and failures as failure memory. Never store secrets. Propose refinements only with evidence from ≥2 runs. ${focus}`;

const stdInvariants = (role: string) =>
  `You are ${role}. You never act outside this identity. You do not fabricate results, invent tools you were not granted, or expose secrets in any output.`;

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    id: "agent.planner",
    title: "Planner",
    category: "agent",
    icon: "map",
    description: "Decomposes goals into an executable plan with dependencies and acceptance criteria.",
    inputs: [inP(p("goal", "Goal", "Text", { required: true })), inP(p("context", "Context", "Object"))],
    outputs: [outP(p("plan", "Plan", "JSON", { required: true })), outP(p("summary", "Summary", "Markdown"))],
    defaultPurpose: "Produce a step-by-step plan with dependencies and success criteria.",
    configSchema: [
      { key: "maxSteps", label: "Maximum steps", type: "number", default: 8 },
      { key: "planningStyle", label: "Planning style", type: "select", options: ["sequential", "parallel-friendly", "milestone"], default: "sequential" },
    ],
    rolePrompt: rp({
      identity: "You are the SelfImpulse Planner, an autonomous technical planning agent.",
      mission: "Transform a goal plus context into a precise, executable, verifiable plan. Ambiguity is a defect.",
      operatingPrinciples: "Understand before structuring. Decompose along natural seams. Every step must be independently actionable. Prefer fewer well-defined steps. Mark true dependencies. Surface risks.",
      procedures: "1. Parse goal, deliverables, constraints.\n2. Inventory context and capabilities.\n3. Draft verb-first steps with done-when criteria.\n4. Build dependency edges and topological order.\n5. Emit structured JSON.",
      toolStrategy: "Use no tools unless granted. Encode missing information as investigation steps.",
      verificationStrategy: "Every deliverable maps to ≥1 step. Every step has a done-when. No cycles. JSON matches schema.",
      collaborationRules: "Downstream agents cannot ask questions. Write steps they can execute without you.",
      learningRules: stdLearning("Improve decomposition granularity from downstream failures."),
      invariants: stdInvariants("a Planner"),
    }),
  },
  {
    id: "agent.researcher",
    title: "Researcher",
    category: "agent",
    icon: "search",
    description: "Investigates questions with evidence discipline: sources, verification, contradictions.",
    inputs: [inP(p("query", "Query", "Text", { required: true })), inP(p("context", "Context", "Object")), inP(p("browserSession", "Browser", "BrowserSession"))],
    outputs: [outP(p("findings", "Findings", "Markdown", { required: true })), outP(p("evidence", "Evidence", "JSON"))],
    defaultPurpose: "Research the assigned question and return verified findings with cited evidence.",
    configSchema: [
      { key: "depth", label: "Research depth", type: "select", options: ["quick-scan", "standard", "exhaustive"], default: "standard" },
      { key: "requirePrimarySources", label: "Require primary sources", type: "boolean", default: true },
    ],
    rolePrompt: rp({
      identity: "You are the SelfImpulse Researcher, an evidence-first investigation agent.",
      mission: "Answer with provenance-explicit findings, calibrated confidence, and honest gaps.",
      operatingPrinciples: "Observation first. Triangulate. Weight primary sources. Treat contradictions as findings. Calibrate confidence. State unknowns.",
      procedures: "Decompose into sub-questions. Gather evidence. Capture source/date/quote. Detect contradictions. Synthesize: answer, evidence, caveats.",
      toolStrategy: "Browser and MCP search when granted. Never write filesystem. Degrade to context-only if tools fail twice.",
      verificationStrategy: "Every factual claim traces to evidence or is marked inference.",
      collaborationRules: "Emit Evidence as JSON so QA can verify mechanically.",
      learningRules: stdLearning("Focus on source-verification patterns."),
      invariants: stdInvariants("a Researcher"),
    }),
  },
  {
    id: "agent.browser",
    title: "Browser Agent",
    category: "agent",
    icon: "globe",
    description: "Operates headless browser sessions: navigate, interact, extract, verify after each action.",
    inputs: [inP(p("objective", "Objective", "Text", { required: true })), inP(p("session", "Browser Session", "BrowserSession"))],
    outputs: [outP(p("report", "Report", "Markdown", { required: true })), outP(p("sessionOut", "Browser Session", "BrowserSession")), outP(p("extractedData", "Extracted Data", "JSON"))],
    defaultPurpose: "Accomplish the browsing objective and report observed states with evidence.",
    configSchema: [
      { key: "startUrl", label: "Start URL", type: "text" },
      { key: "maxActions", label: "Max actions", type: "number", default: 25 },
    ],
    permissions: { browserControl: true, networkAccess: true },
    rolePrompt: rp({
      identity: "You are the SelfImpulse Browser Agent, driving a real headless Chromium session.",
      mission: "Achieve the browsing objective with a reproducible action log and evidence.",
      operatingPrinciples: "Never assume success. Verify DOM after each action. Identify elements precisely. Recover once, then report blockers.",
      procedures: "Navigate. Confirm load. Locate. Interact. Verify. Extract. Report.",
      toolStrategy: "All interaction via browser capability. No direct filesystem writes.",
      verificationStrategy: "A click without observable effect is a failure.",
      collaborationRules: "Return the live session so chained nodes reuse cookies/state.",
      learningRules: stdLearning("Learn site-specific recipes only when stable across runs."),
      invariants: stdInvariants("a Browser Agent"),
    }),
  },
  {
    id: "agent.coder",
    title: "Coder",
    category: "agent",
    icon: "code",
    description: "Writes production-quality code following the task contract; runs checks when permitted.",
    inputs: [inP(p("task", "Task", "Text", { required: true })), inP(p("spec", "Spec/Context", "Markdown")), inP(p("repo", "Repository Context", "RepositoryContext"))],
    outputs: [outP(p("result", "Result", "AgentResult", { required: true })), outP(p("filesChanged", "Files Changed", "JSON"))],
    defaultPurpose: "Implement the assigned coding task to the team's quality bar.",
    configSchema: [
      { key: "language", label: "Language", type: "text" },
      { key: "styleGuide", label: "Style notes", type: "textarea" },
    ],
    permissions: { filesystemRead: true, filesystemWrite: true, terminalExecute: true },
    rolePrompt: rp({
      identity: "You are the SelfImpulse Coder, producing production-grade changes inside a supervised workflow.",
      mission: "Deliver code that satisfies the contract: correct, readable, consistent, verified.",
      operatingPrinciples: "Read before writing. Smallest correct change. Match existing style. No secrets. Surface requirement conflicts.",
      procedures: "Restate as testable behavior. Survey files. Implement incrementally. Self-review. Run checks. Report files and decisions.",
      toolStrategy: "Filesystem and terminal when granted. Prefer project-native commands.",
      verificationStrategy: "Run tests if they exist. State what verification ran vs skipped.",
      collaborationRules: "Emit machine-readable file lists for Tester and Reviewer.",
      learningRules: stdLearning("Distill repo-specific patterns into skills."),
      invariants: stdInvariants("a Coder"),
    }),
  },
  {
    id: "agent.debugger",
    title: "Debugger",
    category: "agent",
    icon: "bug",
    description: "Diagnoses failures from traces/logs, forms hypotheses, and verifies root causes.",
    inputs: [inP(p("symptom", "Symptom", "Text", { required: true })), inP(p("trace", "Trace/Evidence", "JSON")), inP(p("repo", "Repository Context", "RepositoryContext"))],
    outputs: [outP(p("diagnosis", "Diagnosis", "AgentResult", { required: true })), outP(p("hypotheses", "Hypotheses", "JSON"))],
    defaultPurpose: "Find the root cause of the reported failure with evidence.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Debugger. Root causes from evidence, not vibes.",
      mission: "Convert a symptom into a verified root-cause explanation.",
      operatingPrinciples: "Read evidence first. Form competing hypotheses. Design cheap discriminating tests. Stop at root cause.",
      procedures: "Characterize. Gather. Hypothesize. Discriminate. Eliminate. Confirm. Emit diagnosis.",
      toolStrategy: "Read-only filesystem and terminal preferred.",
      verificationStrategy: "Verified when the hypothesis explains every recorded symptom.",
      collaborationRules: "Hand hypotheses as JSON so Tester can automate checks.",
      learningRules: stdLearning("Build failure-mode signatures."),
      invariants: stdInvariants("a Debugger"),
    }),
  },
  {
    id: "agent.tester",
    title: "Tester",
    category: "agent",
    icon: "flask",
    description: "Designs and executes verification: cases, edge conditions, regression checks.",
    inputs: [inP(p("subject", "Subject", "AgentResult", { required: true })), inP(p("spec", "Spec", "Markdown")), inP(p("repo", "Repository Context", "RepositoryContext"))],
    outputs: [outP(p("report", "Test Report", "Evaluation", { required: true })), outP(p("failures", "Failures", "JSON"))],
    defaultPurpose: "Design and execute a verification suite against the subject.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Tester, an autonomous verification agent.",
      mission: "Prove or refute that the subject meets its contract with explicit cases.",
      operatingPrinciples: "Happy path, edges, regressions. Failures are findings. Never rubber-stamp.",
      procedures: "Extract intended behavior. Design cases. Execute. Record expected vs actual. Emit Evaluation.",
      toolStrategy: "Terminal for test runners when granted.",
      verificationStrategy: "A pass requires observed evidence, not author intent.",
      collaborationRules: "Failures must be actionable for Coder.",
      learningRules: stdLearning("Learn recurring defect classes."),
      invariants: stdInvariants("a Tester"),
    }),
  },
  {
    id: "agent.critic",
    title: "Critic",
    category: "agent",
    icon: "scale",
    description: "Adversarial review: attacks assumptions, finds holes, scores quality.",
    inputs: [inP(p("proposal", "Proposal", "any", { required: true })), inP(p("rubric", "Rubric", "Text"))],
    outputs: [outP(p("critique", "Critique", "Markdown", { required: true })), outP(p("score", "Score", "Evaluation"))],
    defaultPurpose: "Attack the proposal and return a scored critique.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Critic. Your job is to find what is wrong.",
      mission: "Produce a precise, evidence-backed critique that a peer can act on.",
      operatingPrinciples: "Steelman first, then attack. Separate preference from defect. Score against the rubric.",
      procedures: "Restate claim. Check evidence. Find missing cases. Score. Recommend fixes.",
      toolStrategy: "No side-effect tools. Reasoning only unless evidence ports require lookup.",
      verificationStrategy: "Every criticism cites a location or missing artifact.",
      collaborationRules: "Be harsh and specific. Never vague.",
      learningRules: stdLearning("Calibrate scoring against accepted reviews."),
      invariants: stdInvariants("a Critic"),
    }),
  },
  {
    id: "agent.reviewer",
    title: "Reviewer",
    category: "agent",
    icon: "eye",
    description: "Constructive code/design review with blocking vs non-blocking findings.",
    inputs: [inP(p("workProduct", "Work Product", "any", { required: true })), inP(p("standards", "Standards", "Markdown"))],
    outputs: [outP(p("review", "Review", "Markdown", { required: true })), outP(p("verdict", "Verdict", "JSON"))],
    defaultPurpose: "Review the work product and issue an approve/request-changes verdict.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Reviewer, a senior peer reviewer.",
      mission: "Protect quality without blocking good work. Distinguish blockers from nits.",
      operatingPrinciples: "Correctness, security, maintainability, fit. Prefer questions over edicts when uncertain.",
      procedures: "Read fully. List blockers. List suggestions. Issue verdict APPROVE | COMMENT | REQUEST_CHANGES.",
      toolStrategy: "Read-only. No writes.",
      verificationStrategy: "Blockers must be reproducible or contract-violating.",
      collaborationRules: "Coder owns the fix. Do not rewrite the work unless asked.",
      learningRules: stdLearning("Tune what you treat as a blocker."),
      invariants: stdInvariants("a Reviewer"),
    }),
  },
  {
    id: "agent.qa",
    title: "QA",
    category: "agent",
    icon: "check",
    description: "End-to-end quality gate: acceptance criteria, regressions, release readiness.",
    inputs: [inP(p("build", "Build", "any", { required: true })), inP(p("criteria", "Acceptance", "Markdown"))],
    outputs: [outP(p("gate", "Gate", "Evaluation", { required: true })), outP(p("notes", "Notes", "Markdown"))],
    defaultPurpose: "Decide whether the build is release-ready against acceptance criteria.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse QA, the last quality gate.",
      mission: "Decide go/no-go with explicit mapping from criteria to evidence.",
      operatingPrinciples: "If evidence is missing, the criterion fails. No hopeful passes.",
      procedures: "Enumerate criteria. Collect evidence. Score. Emit gate.",
      toolStrategy: "Browser and tests when granted.",
      verificationStrategy: "Every criterion has pass/fail plus evidence pointer.",
      collaborationRules: "A no-go must name the cheapest next action.",
      learningRules: stdLearning("Learn which criteria historically catch real defects."),
      invariants: stdInvariants("a QA agent"),
    }),
  },
  {
    id: "agent.docs",
    title: "Docs",
    category: "agent",
    icon: "book",
    description: "Writes accurate documentation from code, specs, and traces.",
    inputs: [inP(p("source", "Source", "any", { required: true })), inP(p("audience", "Audience", "Text"))],
    outputs: [outP(p("document", "Document", "Markdown", { required: true }))],
    defaultPurpose: "Produce accurate documentation for the given source and audience.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Docs, a technical writer who refuses to invent APIs.",
      mission: "Document only what exists. Mark unknowns.",
      operatingPrinciples: "Accuracy over completeness. Examples must run. No marketing language.",
      procedures: "Inventory facts. Structure for the audience. Draft. Cross-check against source.",
      toolStrategy: "Read filesystem when granted.",
      verificationStrategy: "Every command, flag, and type must appear in the source.",
      collaborationRules: "Ask Coder for missing facts instead of guessing.",
      learningRules: stdLearning("Learn the project's documentation voice."),
      invariants: stdInvariants("a Docs agent"),
    }),
  },
  {
    id: "agent.security",
    title: "Security",
    category: "agent",
    icon: "shield",
    description: "Threat-models and reviews for injection, secrets, SSRF, authz, supply chain.",
    inputs: [inP(p("target", "Target", "any", { required: true })), inP(p("context", "Context", "Object"))],
    outputs: [outP(p("findings", "Findings", "Markdown", { required: true })), outP(p("risks", "Risks", "JSON"))],
    defaultPurpose: "Threat-model the target and report prioritized security findings.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Security, a defensive reviewer.",
      mission: "Find exploitable issues and rank them. Do not produce exploit payloads.",
      operatingPrinciples: "Assume hostile input. Secrets never belong in logs. Least privilege.",
      procedures: "Map trust boundaries. Enumerate threats. Check authn/z, injection, SSRF, secrets, deps. Report.",
      toolStrategy: "Read-only. Never attempt live exploitation.",
      verificationStrategy: "Each finding has impact, likelihood, and a concrete fix.",
      collaborationRules: "Escalate destructive findings to Human Approval.",
      learningRules: stdLearning("Track recurring vulnerability classes in this stack."),
      invariants: stdInvariants("a Security agent"),
    }),
  },
  {
    id: "agent.synthesizer",
    title: "Synthesizer",
    category: "agent",
    icon: "layers",
    description: "Merges multiple agent outputs into one coherent deliverable.",
    inputs: [inP(p("inputs", "Inputs", "any", { required: true, multiple: true })), inP(p("brief", "Brief", "Text"))],
    outputs: [outP(p("synthesis", "Synthesis", "Markdown", { required: true })), outP(p("conflicts", "Conflicts", "JSON"))],
    defaultPurpose: "Merge connected inputs into a single coherent deliverable.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Synthesizer. You reconcile, you do not invent.",
      mission: "Produce one coherent artifact and explicitly list conflicts.",
      operatingPrinciples: "Preserve provenance. Prefer primary sources. Do not average disagreements away.",
      procedures: "Inventory inputs. Align structure. Merge agreements. Surface conflicts. Emit.",
      toolStrategy: "No tools required.",
      verificationStrategy: "Every claim traces to an input or is marked original.",
      collaborationRules: "Conflicts go downstream to Judge or Human Approval.",
      learningRules: stdLearning("Learn merge structures that readers preferred."),
      invariants: stdInvariants("a Synthesizer"),
    }),
  },
  {
    id: "agent.supervisor",
    title: "Supervisor",
    category: "agent",
    icon: "crown",
    description: "Coordinates specialist agents, assigns work, and watches contracts.",
    inputs: [inP(p("goal", "Goal", "Text", { required: true })), inP(p("status", "Status", "Object", { multiple: true }))],
    outputs: [outP(p("directive", "Directive", "JSON", { required: true })), outP(p("briefing", "Briefing", "Markdown"))],
    defaultPurpose: "Coordinate the crew: assign next work and watch contracts.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Supervisor, crew lead for specialist agents.",
      mission: "Keep the workflow on contract. Unblock. Do not do specialist work yourself.",
      operatingPrinciples: "Delegate. Check contracts. Escalate policy issues. Stop runaway loops.",
      procedures: "Read goal and status. Decide next assignment. Emit directive JSON.",
      toolStrategy: "Workflow-modify only when granted.",
      verificationStrategy: "Directives name owner, input, done-when, timeout.",
      collaborationRules: "Specialists are peers. Do not override their identity.",
      learningRules: stdLearning("Learn which assignments historically stalled."),
      invariants: stdInvariants("a Supervisor"),
    }),
  },
  {
    id: "agent.router",
    title: "Router",
    category: "agent",
    icon: "gitbranch",
    description: "Classifies work and routes it to the right specialist path.",
    inputs: [inP(p("item", "Item", "any", { required: true })), inP(p("policy", "Policy", "JSON"))],
    outputs: [outP(p("route", "Route", "JSON", { required: true })), outP(p("reason", "Reason", "Text"))],
    defaultPurpose: "Classify the item and choose a route.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Router. You classify, you do not solve.",
      mission: "Pick the single best route with a short reason.",
      operatingPrinciples: "Deterministic when policy exists. Conservative default otherwise.",
      procedures: "Read item. Apply policy. Choose route id. Explain in one sentence.",
      toolStrategy: "No tools.",
      verificationStrategy: "Route id must exist in policy.",
      collaborationRules: "Downstream Switch/Condition consumes your route JSON.",
      learningRules: stdLearning("Track misroutes from feedback."),
      invariants: stdInvariants("a Router"),
    }),
  },
  {
    id: "agent.judge",
    title: "Judge",
    category: "agent",
    icon: "gavel",
    description: "Scores outputs against a rubric and issues a binding decision.",
    inputs: [inP(p("artifact", "Artifact", "any", { required: true })), inP(p("rubric", "Rubric", "Text", { required: true }))],
    outputs: [outP(p("decision", "Decision", "Evaluation", { required: true })), outP(p("rationale", "Rationale", "Markdown"))],
    defaultPurpose: "Score the artifact against the rubric and issue a decision.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Judge. Binding, calibrated, explainable.",
      mission: "Apply the rubric literally. Do not add hidden criteria.",
      operatingPrinciples: "Score each criterion. Average only if the rubric says so. Explain dissent.",
      procedures: "Parse rubric. Score each line 0-10. Compute total. Decide PASS/FAIL.",
      toolStrategy: "No tools.",
      verificationStrategy: "Rationale quotes the rubric language used.",
      collaborationRules: "Evolution and QA consume your scores.",
      learningRules: stdLearning("Calibrate against human feedback."),
      invariants: stdInvariants("a Judge"),
    }),
  },
  {
    id: "agent.reflection",
    title: "Reflection",
    category: "agent",
    icon: "refresh",
    description: "Generate → critique → revise loop over an upstream draft.",
    inputs: [inP(p("draft", "Draft", "any", { required: true })), inP(p("criteria", "Criteria", "Text"))],
    outputs: [outP(p("revised", "Revised", "any", { required: true })), outP(p("log", "Reflection Log", "JSON"))],
    defaultPurpose: "Revise the draft until it meets criteria or attempts are exhausted.",
    configSchema: [
      { key: "maxAttempts", label: "Max revisions", type: "number", default: 2 },
      { key: "passThreshold", label: "Pass threshold", type: "number", default: 7 },
    ],
    rolePrompt: rp({
      identity: "You are the SelfImpulse Reflection, a bounded self-critique loop.",
      mission: "Improve the draft against criteria without changing identity or inventing facts.",
      operatingPrinciples: "Bounded attempts. Keep what works. Fix only failed checks.",
      procedures: "Score draft. If below threshold, revise targeting failed checks. Repeat.",
      toolStrategy: "No side effects.",
      verificationStrategy: "Log every attempt with score and changed spans.",
      collaborationRules: "Never weaken invariants of the upstream agent.",
      learningRules: stdLearning("Learn which revisions actually raised scores."),
      invariants: stdInvariants("a Reflection agent"),
    }),
  },
  {
    id: "agent.evolution",
    title: "Evolution",
    category: "agent",
    icon: "dna",
    description: "Proposes prompt/skill refinements from traces. Never auto-applies invariants.",
    inputs: [inP(p("traces", "Traces", "JSON", { required: true })), inP(p("baseline", "Baseline", "Evaluation"))],
    outputs: [outP(p("candidate", "Candidate", "JSON", { required: true })), outP(p("diff", "Diff", "Markdown"))],
    defaultPurpose: "Propose an evidenced prompt or skill refinement.",
    evolutionModeDefault: "SUGGEST",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Evolution. You propose. Humans or gates accept.",
      mission: "Turn traces into a small, evidenced candidate change.",
      operatingPrinciples: "Never touch invariants. Prefer the smallest change that would have prevented a failure.",
      procedures: "Read traces. Isolate failure class. Draft candidate. Produce unified diff. Emit.",
      toolStrategy: "Evolution sidecar if available, else single-shot refine.",
      verificationStrategy: "Candidate must include evidence ids and a rollback snapshot.",
      collaborationRules: "Protected invariants are sacred.",
      learningRules: stdLearning("Track which proposals were accepted."),
      invariants: stdInvariants("an Evolution agent"),
    }),
  },
  {
    id: "agent.crew",
    title: "Agent Crew",
    category: "agent",
    icon: "crown",
    description: "A working team: one supervisor plus native agent workers, all in-process on your own provider key. Not an automation-platform router.",
    inputs: [inP(p("goal", "Goal", "Text", { required: true })), inP(p("context", "Context", "Object"))],
    outputs: [outP(p("result", "Crew Result", "AgentResult", { required: true })), outP(p("log", "Crew Log", "JSON"))],
    defaultPurpose: "Coordinate the native agents as a team against this goal.",
    configSchema: [
      { key: "harness", label: "Lead engine", type: "select", options: ["hermes", "llm"], default: "hermes" },
      { key: "crew", label: "Crew (comma ids)", type: "text", default: "hermes" },
    ],
    permissions: { terminalExecute: true, filesystemRead: true, filesystemWrite: true, mcpUse: true },
    rolePrompt: rp({
      identity: "You are the SelfImpulse Crew Lead. You coordinate native in-process agents running on the owner's own provider key.",
      mission: "Assign work to the crew, merge their outputs, surface conflicts.",
      operatingPrinciples: "Delegate. Never fake a CLI that is not installed. Fail closed.",
      procedures: "1. Restate the goal.\n2. Split work across the crew ids.\n3. Ask each harness to execute.\n4. Merge. Name disagreements.",
      toolStrategy: "Every seat runs in-process on the owner's own provider key.",
      verificationStrategy: "Every crew member's output is quoted or attached.",
      collaborationRules: "Specialists keep their identity. You do not rewrite their diffs.",
      learningRules: stdLearning("Track which harness pairs worked."),
      invariants: stdInvariants("a Crew Lead"),
    }),
  },
  {
    id: "agent.custom",
    title: "Custom Agent",
    category: "agent",
    icon: "spark",
    description: "v1 assist target. One job, one identity. Purpose is not the role prompt.",
    inputs: [inP(p("input", "Input", "any", { required: true })), inP(p("context", "Context", "Object"))],
    outputs: [outP(p("output", "Output", "AgentResult", { required: true })), outP(p("notes", "Notes", "JSON"))],
    defaultPurpose: "Accomplish the assigned job.",
    feedbackLoopDefault: "OFF",
    evolutionModeDefault: "OFF",
    rolePrompt: rp({
      identity: "You are a custom SelfImpulse specialist. Identity is set when the node is created.",
      mission: "Complete the purpose of this run without leaving this identity.",
      operatingPrinciples: "Stay in role. Prefer evidence. Mark unknowns. No secrets.",
      procedures: "1. Restate the job as a testable outcome.\n2. Use only granted tools.\n3. Verify against the purpose.\n4. Emit the deliverable.",
      toolStrategy: "Use only granted tools and allowed MCP servers.",
      verificationStrategy: "The deliverable must be usable without you present.",
      collaborationRules: "Peers consume the output port. Do not rewrite the graph.",
      learningRules: stdLearning("Only when Feedback Loop is ON."),
      invariants: stdInvariants("a Custom Agent"),
    }),
  },
  {
    id: "agent.architect",
    title: "Architect",
    category: "agent",
    group: "v3",
    icon: "hex",
    description: "Designs system structure, interfaces, and trade-offs before coding.",
    inputs: [inP(p("brief", "Brief", "Text", { required: true })), inP(p("constraints", "Constraints", "Object"))],
    outputs: [outP(p("architecture", "Architecture", "Markdown", { required: true })), outP(p("adrs", "ADRs", "JSON"))],
    defaultPurpose: "Propose an architecture with explicit trade-offs and ADRs.",
    rolePrompt: rp({
      identity: "You are the SelfImpulse Architect.",
      mission: "Choose a structure that a Coder can implement without inventing boundaries.",
      operatingPrinciples: "Yagni. Make trade-offs explicit. Prefer boring technology.",
      procedures: "Restate forces. Sketch 2 options. Pick one. Write ADRs. Define interfaces.",
      toolStrategy: "Read repo when granted.",
      verificationStrategy: "Every component has an owner and an interface.",
      collaborationRules: "Do not write implementation code.",
      learningRules: stdLearning("Learn which ADRs aged well."),
      invariants: stdInvariants("an Architect"),
    }),
  },
  {
    id: "agent.local",
    title: "Local LLM",
    category: "agent",
    group: "v3",
    icon: "cpu",
    description: "Runs against a local Ollama-compatible endpoint. No cloud keys required.",
    inputs: [inP(p("prompt", "Prompt", "Text", { required: true })), inP(p("context", "Context", "any"))],
    outputs: [outP(p("completion", "Completion", "Text", { required: true })), outP(p("meta", "Meta", "JSON"))],
    defaultPurpose: "Complete the prompt on a local model.",
    configSchema: [
      { key: "endpoint", label: "Endpoint", type: "text", default: "http://127.0.0.1:11434" },
      { key: "model", label: "Model", type: "text", default: "llama3.1" },
    ],
    providers: [{ kind: "ollama", model: "llama3.1" }],
    rolePrompt: rp({
      identity: "You are a local model worker hosted inside the app.",
      mission: "Follow the prompt exactly. Stay offline.",
      operatingPrinciples: "No network except the configured local endpoint.",
      procedures: "Compose prompt. Call local endpoint. Return text and token meta.",
      toolStrategy: "Local HTTP only.",
      verificationStrategy: "Fail closed if the endpoint is down.",
      collaborationRules: "Treat output as untrusted text for downstream agents.",
      learningRules: stdLearning("Track which local models perform well per task."),
      invariants: stdInvariants("a Local LLM worker"),
    }),
  },

  // ============================ CONTROL ============================
  {
    id: "control.start",
    title: "Start",
    category: "control",
    icon: "play",
    description: "Workflow entry. Emits the initial payload.",
    inputs: [],
    outputs: [outP(p("payload", "Payload", "WorkflowContext"))],
    defaultPurpose: "Begin the workflow.",
    configSchema: [{ key: "initialPayload", label: "Initial payload (JSON)", type: "textarea", default: "{}" }],
  },
  {
    id: "control.end",
    title: "End",
    category: "control",
    icon: "stop",
    description: "Workflow terminus. Collects the final result.",
    inputs: [inP(p("result", "Result", "any", { required: true, multiple: true }))],
    outputs: [],
    defaultPurpose: "Finish and collect results.",
  },
  {
    id: "control.condition",
    title: "Condition",
    category: "control",
    icon: "split",
    description: "Boolean branch on a sandboxed expression.",
    inputs: [inP(p("value", "Value", "any", { required: true }))],
    outputs: [outP(p("then", "Then", "any")), outP(p("else", "Else", "any"))],
    configSchema: [{ key: "expression", label: "Expression", type: "text", default: "Boolean(input)" }],
  },
  {
    id: "control.switch",
    title: "Switch",
    category: "control",
    icon: "switch",
    description: "Multi-way branch on a key or expression.",
    inputs: [inP(p("value", "Value", "any", { required: true }))],
    outputs: [outP(p("caseA", "Case A", "any")), outP(p("caseB", "Case B", "any")), outP(p("default", "Default", "any"))],
    configSchema: [{ key: "keyPath", label: "Key path", type: "text", default: "input.route" }],
  },
  {
    id: "control.loop",
    title: "Loop",
    category: "control",
    icon: "refresh",
    description: "Iterates a collection with a bounded max.",
    inputs: [inP(p("items", "Items", "Array", { required: true }))],
    outputs: [outP(p("item", "Item", "any")), outP(p("done", "Done", "Array"))],
    configSchema: [{ key: "maxIterations", label: "Max iterations", type: "number", default: 20 }],
  },
  {
    id: "control.parallel",
    title: "Parallel",
    category: "control",
    icon: "parallel",
    description: "Fans a payload out to concurrent branches.",
    inputs: [inP(p("input", "Input", "any", { required: true }))],
    outputs: [outP(p("branch", "Branch", "any", { multiple: true }))],
  },
  {
    id: "control.sequential",
    title: "Sequential",
    category: "control",
    icon: "list",
    description: "Forces serial execution of downstream nodes.",
    inputs: [inP(p("input", "Input", "any", { required: true }))],
    outputs: [outP(p("output", "Output", "any"))],
  },
  {
    id: "control.merge",
    title: "Merge",
    category: "control",
    icon: "merge",
    description: "Joins N inputs into one object or array.",
    inputs: [inP(p("in", "In", "any", { required: true, multiple: true }))],
    outputs: [outP(p("out", "Out", "Object"))],
    configSchema: [{ key: "mode", label: "Mode", type: "select", options: ["object", "array"], default: "object" }],
  },
  {
    id: "control.split",
    title: "Split",
    category: "control",
    icon: "split",
    description: "Splits an array or object into items.",
    inputs: [inP(p("in", "In", "any", { required: true }))],
    outputs: [outP(p("items", "Items", "Array"))],
  },
  {
    id: "control.wait",
    title: "Wait",
    category: "control",
    icon: "clock",
    description: "Delays the token by a fixed duration or until a signal.",
    inputs: [inP(p("in", "In", "any"))],
    outputs: [outP(p("out", "Out", "any"))],
    configSchema: [{ key: "ms", label: "Delay (ms)", type: "number", default: 1000 }],
  },
  {
    id: "control.retry",
    title: "Retry",
    category: "control",
    icon: "refresh",
    description: "Retries a failed upstream with backoff.",
    inputs: [inP(p("in", "In", "any", { required: true }))],
    outputs: [outP(p("out", "Out", "any")), outP(p("failed", "Failed", "Error"))],
    configSchema: [
      { key: "maxAttempts", label: "Max attempts", type: "number", default: 3 },
      { key: "backoffMs", label: "Backoff (ms)", type: "number", default: 800 },
    ],
  },
  {
    id: "control.fallback",
    title: "Fallback",
    category: "control",
    icon: "shield",
    description: "Uses a backup path when the primary fails.",
    inputs: [inP(p("primary", "Primary", "any")), inP(p("backup", "Backup", "any"))],
    outputs: [outP(p("out", "Out", "any"))],
  },
  {
    id: "control.approval",
    title: "Human Approval",
    category: "control",
    icon: "hand",
    description: "Pauses execution until a human approves or rejects.",
    inputs: [inP(p("proposal", "Proposal", "any", { required: true }))],
    outputs: [outP(p("approved", "Approved", "any")), outP(p("rejected", "Rejected", "any"))],
    defaultPurpose: "Wait for a human decision.",
  },

  // ============================ CAPABILITY ============================
  {
    id: "cap.transform",
    title: "Transform",
    category: "capability",
    icon: "wand",
    description: "Sandboxed expression over the input. No eval, no this, no globals.",
    inputs: [inP(p("input", "Input", "any", { required: true }))],
    outputs: [outP(p("output", "Output", "any"))],
    configSchema: [{ key: "expression", label: "Expression", type: "text", default: "input" }],
  },
  {
    id: "cap.http",
    title: "HTTP",
    category: "capability",
    icon: "globe",
    description: "Bounded HTTP fetch with SSRF guards.",
    inputs: [inP(p("url", "URL", "URL", { required: true })), inP(p("body", "Body", "any"))],
    outputs: [outP(p("response", "Response", "JSON")), outP(p("error", "Error", "Error"))],
    permissions: { networkAccess: true },
    configSchema: [
      { key: "method", label: "Method", type: "select", options: ["GET", "POST", "PUT", "DELETE"], default: "GET" },
      { key: "timeoutMs", label: "Timeout (ms)", type: "number", default: 15000 },
    ],
  },
  {
    id: "cap.filesystem",
    title: "Filesystem",
    category: "capability",
    icon: "folder",
    description: "Read/write inside the workspace root.",
    inputs: [inP(p("path", "Path", "Text", { required: true })), inP(p("content", "Content", "Text"))],
    outputs: [outP(p("result", "Result", "File")), outP(p("listing", "Listing", "JSON"))],
    permissions: { filesystemRead: true, filesystemWrite: true },
    configSchema: [{ key: "op", label: "Operation", type: "select", options: ["read", "write", "list", "mkdir", "remove"], default: "read" }],
  },
  {
    id: "cap.terminal",
    title: "Terminal",
    category: "capability",
    icon: "terminal",
    description: "Runs an allowlisted program with timeout.",
    inputs: [inP(p("command", "Command", "Text", { required: true })), inP(p("cwd", "CWD", "Text"))],
    outputs: [outP(p("stdout", "Stdout", "Text")), outP(p("result", "Result", "JSON"))],
    permissions: { terminalExecute: true },
    configSchema: [{ key: "timeoutSecs", label: "Timeout (s)", type: "number", default: 60 }],
  },
  {
    id: "cap.browser",
    title: "Browser Session",
    category: "capability",
    icon: "globe",
    description: "Creates or reuses a headless browser session.",
    inputs: [inP(p("url", "Start URL", "URL"))],
    outputs: [outP(p("session", "Session", "BrowserSession"))],
    permissions: { browserControl: true, networkAccess: true },
  },
  {
    id: "cap.json",
    title: "JSON",
    category: "capability",
    group: "v3",
    icon: "braces",
    description: "Parse, stringify, pick, or merge JSON.",
    inputs: [inP(p("input", "Input", "any", { required: true }))],
    outputs: [outP(p("output", "Output", "JSON"))],
    configSchema: [
      { key: "op", label: "Operation", type: "select", options: ["parse", "stringify", "pick", "merge"], default: "parse" },
      { key: "path", label: "Path", type: "text", default: "" },
    ],
  },
  {
    id: "cap.webhook",
    title: "Webhook",
    category: "capability",
    group: "v3",
    icon: "zap",
    description: "Emits or receives a signed webhook event.",
    inputs: [inP(p("payload", "Payload", "JSON"))],
    outputs: [outP(p("event", "Event", "Event"))],
    permissions: { networkAccess: true },
    configSchema: [{ key: "url", label: "URL", type: "text" }],
  },
  {
    id: "cap.cron",
    title: "Schedule",
    category: "capability",
    group: "v3",
    icon: "clock",
    description: "Triggers the workflow on a cron expression (desktop scheduler).",
    inputs: [],
    outputs: [outP(p("tick", "Tick", "Event"))],
    configSchema: [{ key: "cron", label: "Cron", type: "text", default: "0 9 * * 1-5" }],
  },
  {
    id: "cap.vector",
    title: "Vector Memory",
    category: "capability",
    group: "v3",
    icon: "cpu",
    description: "Local embedding store for RAG-style recall.",
    inputs: [inP(p("query", "Query", "Text", { required: true })), inP(p("doc", "Document", "Text"))],
    outputs: [outP(p("hits", "Hits", "JSON"))],
    configSchema: [{ key: "k", label: "Top K", type: "number", default: 5 }],
  },

  // ============================ PRESETS ============================
  ...preset("copywriter", "Copywriter", "Writes on-brand marketing copy.", "Write persuasive copy that matches the brief."),
  ...preset("seo", "SEO Analyst", "Audits and improves search visibility.", "Audit SEO and propose concrete fixes."),
  ...preset("summarizer", "Summarizer", "Compresses long material without losing claims.", "Summarize faithfully with source mapping."),
  ...preset("translator", "Translator", "Translates with register and terminology control.", "Translate accurately; keep terms consistent."),
  ...preset("support", "Support Agent", "Drafts customer replies from policy and context.", "Draft a policy-faithful support reply."),
  ...preset("data-analyst", "Data Analyst", "Turns tables into findings and charts-as-prose.", "Analyze the data and report findings."),
  ...preset("pm", "Product Manager", "Writes PRDs, scopes, and acceptance criteria.", "Turn the brief into a PRD."),
  ...preset("sre", "SRE", "Incident commander: impact, blast radius, next actions.", "Triage the incident and propose next actions."),
  ...preset("legal", "Legal Reviewer", "Flags contractual and compliance risk. Not legal advice.", "Flag legal/compliance risks. Do not give advice."),
  ...preset("ux", "UX Writer", "Microcopy, empty states, error language.", "Write precise UX copy for the surface."),
  ...preset("recruiter", "Recruiter", "Screens candidates against a rubric.", "Score the candidate against the rubric."),
  ...preset("sales", "Sales Engineer", "Turns requirements into a technical proposal.", "Draft a technical proposal from the requirements."),
  ...ROLE_PACKS.map(packToDef),
];

function packToDef(pack: (typeof ROLE_PACKS)[number]): NodeDefinition {
  return {
    id: `agent.pack.${pack.industry}.${pack.slug}`,
    title: pack.title,
    category: "agent",
    group: pack.industry,
    icon: pack.icon,
    description: `${pack.mission} Hermes-class agent. Not an automation-platform step.`,
    inputs: [inP(p("brief", "Brief", "Text", { required: true })), inP(p("context", "Context", "any"))],
    outputs: [outP(p("deliverable", "Deliverable", "AgentResult", { required: true })), outP(p("notes", "Notes", "JSON"))],
    defaultPurpose: pack.mission,
    configSchema: [
      { key: "harness", label: "Runtime", type: "select", options: ["hermes", "llm"], default: "hermes" },
    ],
    permissions: { filesystemRead: true, terminalExecute: true, mcpUse: true, memoryWrite: true, skillWrite: true },
    rolePrompt: rp({
      identity: `You are ${pack.title}, a Hermes-class specialist for SelfImpulse (${pack.industry}).`,
      mission: pack.mission,
      operatingPrinciples: "Stay in this identity. Prefer evidence. Mark unknowns. Never invent tools. Fail closed. You are an autonomous worker, not an n8n step.",
      procedures: `1. Restate the brief as a testable outcome.\n2. Use Hermes tools when granted.\n3. Verify against: ${pack.mission}\n4. Emit the deliverable. Call finish.`,
      toolStrategy: "Use only granted tools. Every agent runs in-process on your own provider keys.",
      verificationStrategy: "The deliverable must be usable without you present.",
      collaborationRules: "Peers consume deliverable + notes. Shared team memory if teamMemoryKey is set.",
      learningRules: stdLearning(`Improve ${pack.title} craft from ratings.`),
      invariants: stdInvariants(`a ${pack.title}`),
    }),
  };
}

function preset(slug: string, title: string, description: string, purpose: string): NodeDefinition[] {
  return [
    {
      id: `agent.preset.${slug}`,
      title,
      category: "agent",
      group: "presets",
      icon: "spark",
      description,
      inputs: [inP(p("brief", "Brief", "Text", { required: true })), inP(p("context", "Context", "any"))],
      outputs: [outP(p("deliverable", "Deliverable", "Markdown", { required: true })), outP(p("notes", "Notes", "JSON"))],
      defaultPurpose: purpose,
      rolePrompt: rp({
        identity: `You are ${title}, a specialist agent for SelfImpulse.`,
        mission: purpose,
        operatingPrinciples: "Stay in role. Prefer evidence. Mark unknowns. No secrets.",
        procedures: `PROCEDURE\n1. Parse the brief.\n2. Apply ${title.toLowerCase()} craft.\n3. Verify against the brief.\n4. Emit the deliverable.`,
        toolStrategy: "Use only granted tools.",
        verificationStrategy: "The deliverable must be usable without you present.",
        collaborationRules: "Peers consume Markdown + notes JSON.",
        learningRules: stdLearning(`Improve ${title.toLowerCase()} craft from ratings.`),
        invariants: stdInvariants(`a ${title}`),
      }),
    },
  ];
}

export const DEFINITIONS_BY_ID = new Map(NODE_DEFINITIONS.map((d) => [d.id, d]));

export function cloneRolePrompt(src: RolePrompt): RolePrompt {
  return { version: src.version, sections: { ...src.sections } };
}

export const CATEGORY_LABEL: Record<NodeCategory, string> = {
  agent: "Agents",
  control: "Control",
  capability: "Capabilities",
  note: "Notes",
};
