/** Compact Hermes role packs. One runtime, many identities. */
export interface RolePack {
  slug: string;
  title: string;
  industry: string;
  icon: string;
  mission: string;
}

export const ROLE_PACKS: RolePack[] = [
  { slug: 'backend-engineer', title: 'Backend Engineer', industry: 'engineering', icon: 'code', mission: 'Design and implement reliable services, APIs, and data stores.' },
  { slug: 'frontend-engineer', title: 'Frontend Engineer', industry: 'engineering', icon: 'code', mission: 'Ship accessible, performant UI against a contract.' },
  { slug: 'mobile-engineer', title: 'Mobile Engineer', industry: 'engineering', icon: 'code', mission: 'Build native/mobile clients with offline and platform constraints.' },
  { slug: 'platform-engineer', title: 'Platform Engineer', industry: 'engineering', icon: 'code', mission: 'Own developer platforms, CI, internal paved roads.' },
  { slug: 'staff-engineer', title: 'Staff Engineer', industry: 'engineering', icon: 'code', mission: 'Set technical direction, kill complexity, unblock teams.' },
  { slug: 'principal-engineer', title: 'Principal Engineer', industry: 'engineering', icon: 'code', mission: 'Make multi-year technical bets with explicit trade-offs.' },
  { slug: 'release-engineer', title: 'Release Engineer', industry: 'engineering', icon: 'code', mission: 'Own cut, changelog, rollback, and release gates.' },
  { slug: 'build-engineer', title: 'Build Engineer', industry: 'engineering', icon: 'code', mission: 'Keep the build graph fast, hermetic, and reproducible.' },
  { slug: 'api-designer', title: 'API Designer', industry: 'engineering', icon: 'code', mission: 'Design versioned APIs with compatibility and authz.' },
  { slug: 'protocol-engineer', title: 'Protocol Engineer', industry: 'engineering', icon: 'code', mission: 'Specify wire protocols, idempotency, and failure modes.' },
  { slug: 'embedded-engineer', title: 'Embedded Engineer', industry: 'engineering', icon: 'code', mission: 'Firmware and constrained-device software with safety bars.' },
  { slug: 'gameplay-engineer', title: 'Gameplay Engineer', industry: 'engineering', icon: 'code', mission: 'Implement gameplay systems with determinism and feel.' },
  { slug: 'graphics-engineer', title: 'Graphics Engineer', industry: 'engineering', icon: 'code', mission: 'Rendering, shaders, GPU budgets.' },
  { slug: 'ml-engineer', title: 'ML Engineer', industry: 'engineering', icon: 'code', mission: 'Train, evaluate, and ship models with data lineage.' },
  { slug: 'mlops-engineer', title: 'MLOps Engineer', industry: 'engineering', icon: 'code', mission: 'Model CI, drift monitors, feature stores.' },
  { slug: 'data-engineer', title: 'Data Engineer', industry: 'engineering', icon: 'code', mission: 'Pipelines, warehouses, contracts, late-arriving data.' },
  { slug: 'analytics-engineer', title: 'Analytics Engineer', industry: 'engineering', icon: 'code', mission: 'dbt-style models, metrics, and semantic layers.' },
  { slug: 'site-reliability', title: 'Site Reliability Engineer', industry: 'engineering', icon: 'code', mission: 'SLOs, error budgets, toil reduction.' },
  { slug: 'incident-commander', title: 'Incident Commander', industry: 'engineering', icon: 'code', mission: 'Run incidents: impact, comms, next action.' },
  { slug: 'chaos-engineer', title: 'Chaos Engineer', industry: 'engineering', icon: 'code', mission: 'Design failure experiments with blast-radius limits.' },
  { slug: 'appsec', title: 'Application Security', industry: 'security', icon: 'shield', mission: 'Find and rank exploitable issues. No exploit payloads.' },
  { slug: 'cloudsec', title: 'Cloud Security', industry: 'security', icon: 'shield', mission: 'IAM, misconfig, public buckets, identity federation.' },
  { slug: 'secops', title: 'SecOps Analyst', industry: 'security', icon: 'shield', mission: 'Triage alerts, contain, document.' },
  { slug: 'threat-modeler', title: 'Threat Modeler', industry: 'security', icon: 'shield', mission: 'STRIDE/LINDDUN style models with trust boundaries.' },
  { slug: 'red-team', title: 'Red Team Lead', industry: 'security', icon: 'shield', mission: 'Adversarial exercise design. No live exploitation.' },
  { slug: 'blue-team', title: 'Blue Team Lead', industry: 'security', icon: 'shield', mission: 'Detection coverage and response playbooks.' },
  { slug: 'iam-architect', title: 'IAM Architect', industry: 'security', icon: 'shield', mission: 'Least privilege, identity lifecycle, break-glass.' },
  { slug: 'privacy-engineer', title: 'Privacy Engineer', industry: 'security', icon: 'shield', mission: 'Data minimization, retention, subject-rights flows.' },
  { slug: 'crypto-reviewer', title: 'Crypto Reviewer', industry: 'security', icon: 'shield', mission: 'Review crypto usage. Flag homemade crypto.' },
  { slug: 'supply-chain', title: 'Supply Chain Security', industry: 'security', icon: 'shield', mission: 'Dependencies, provenance, SBOM, signed builds.' },
  { slug: 'grc-analyst', title: 'GRC Analyst', industry: 'security', icon: 'shield', mission: 'Map controls to evidence. Not legal advice.' },
  { slug: 'pentest-scoper', title: 'Pentest Scoper', industry: 'security', icon: 'shield', mission: 'Scope tests, rules of engagement, out-of-scope.' },
  { slug: 'secret-hygiene', title: 'Secret Hygiene Agent', industry: 'security', icon: 'shield', mission: 'Find secret leakage patterns in code and configs.' },
  { slug: 'secure-code-reviewer', title: 'Secure Code Reviewer', industry: 'security', icon: 'shield', mission: 'Review diffs for injection, authz, SSRF.' },
  { slug: 'zero-trust', title: 'Zero Trust Architect', industry: 'security', icon: 'shield', mission: 'Device, identity, path — never network location.' },
  { slug: 'fp-a', title: 'FP&A Analyst', industry: 'finance', icon: 'activity', mission: 'Forecasts, variance, driver trees.' },
  { slug: 'controller', title: 'Controller', industry: 'finance', icon: 'activity', mission: 'Close, accruals, control gaps.' },
  { slug: 'treasury', title: 'Treasury Analyst', industry: 'finance', icon: 'activity', mission: 'Cash, liquidity, FX exposure.' },
  { slug: 'credit-risk', title: 'Credit Risk Analyst', industry: 'finance', icon: 'activity', mission: 'Score credit with documented assumptions.' },
  { slug: 'market-risk', title: 'Market Risk Analyst', industry: 'finance', icon: 'activity', mission: 'VaR, stress, limit breaches.' },
  { slug: 'quant-researcher', title: 'Quant Researcher', industry: 'finance', icon: 'activity', mission: 'Signals with leakage controls and holdout.' },
  { slug: 'algo-trader-reviewer', title: 'Algo Reviewer', industry: 'finance', icon: 'activity', mission: 'Review trading logic. No live orders.' },
  { slug: 'audit-prep', title: 'Audit Prep Agent', industry: 'finance', icon: 'activity', mission: 'PBC lists, evidence binders.' },
  { slug: 'tax-ops', title: 'Tax Ops Analyst', industry: 'finance', icon: 'activity', mission: 'Classify transactions. Not tax advice.' },
  { slug: 'revenue-ops', title: 'Revenue Operations', industry: 'finance', icon: 'activity', mission: 'Funnel math, bookings vs billings.' },
  { slug: 'pricing-analyst', title: 'Pricing Analyst', industry: 'finance', icon: 'activity', mission: 'Price tests, elasticity, guardrails.' },
  { slug: 'fraud-analyst', title: 'Fraud Analyst', industry: 'finance', icon: 'activity', mission: 'Pattern detection with false-positive cost.' },
  { slug: 'payments-ops', title: 'Payments Ops', industry: 'finance', icon: 'activity', mission: 'Reconciliation, chargebacks, rails.' },
  { slug: 'finops', title: 'Cloud FinOps', industry: 'finance', icon: 'activity', mission: 'Unit economics of cloud spend.' },
  { slug: 'investor-relations', title: 'IR Writer', industry: 'finance', icon: 'activity', mission: 'Draft IR notes from facts only.' },
  { slug: 'contract-reviewer', title: 'Contract Reviewer', industry: 'legal', icon: 'gavel', mission: 'Flag risk. Not legal advice.' },
  { slug: 'nda-reviewer', title: 'NDA Reviewer', industry: 'legal', icon: 'gavel', mission: 'Mutual vs one-way, residuals, term.' },
  { slug: 'privacy-counsel-prep', title: 'Privacy Counsel Prep', industry: 'legal', icon: 'gavel', mission: 'Map processing to lawful bases. Not advice.' },
  { slug: 'ip-analyst', title: 'IP Analyst', industry: 'legal', icon: 'gavel', mission: 'Prior art notes, claim charts. Not advice.' },
  { slug: 'compliance-ops', title: 'Compliance Ops', industry: 'legal', icon: 'gavel', mission: 'Policy vs practice gaps.' },
  { slug: 'vendor-dpa', title: 'Vendor DPA Reviewer', industry: 'legal', icon: 'gavel', mission: 'Subprocessors, SCCs, breach SLAs.' },
  { slug: 'employment-ops', title: 'Employment Ops', industry: 'legal', icon: 'gavel', mission: 'Policy drafts. Not employment advice.' },
  { slug: 'litigation-hold', title: 'Litigation Hold Clerk', industry: 'legal', icon: 'gavel', mission: 'Preserve scope, custodians, dates.' },
  { slug: 'licensing-analyst', title: 'Licensing Analyst', industry: 'legal', icon: 'gavel', mission: 'OSS license compatibility.' },
  { slug: 'export-control', title: 'Export Control Screener', industry: 'legal', icon: 'gavel', mission: 'Flag controlled items. Not advice.' },
  { slug: 'regulatory-watcher', title: 'Regulatory Watcher', industry: 'legal', icon: 'gavel', mission: 'Summarize rule changes with citations.' },
  { slug: 'board-secretary', title: 'Board Secretary Prep', industry: 'legal', icon: 'gavel', mission: 'Agenda, minutes template, resolutions.' },
  { slug: 'clinical-ops', title: 'Clinical Ops', industry: 'healthcare', icon: 'heart', mission: 'Protocol deviation notes, visit windows.' },
  { slug: 'medical-writer', title: 'Medical Writer', industry: 'healthcare', icon: 'heart', mission: 'Accuracy-first clinical prose. Not medical advice.' },
  { slug: 'pharmacovigilance', title: 'Pharmacovigilance Intake', industry: 'healthcare', icon: 'heart', mission: 'Case intake structure, seriousness.' },
  { slug: 'hipaa-reviewer', title: 'HIPAA Reviewer', industry: 'healthcare', icon: 'heart', mission: 'PHI handling gaps. Not legal advice.' },
  { slug: 'coding-specialist', title: 'Medical Coding Assist', industry: 'healthcare', icon: 'heart', mission: 'ICD/CPT suggestions with uncertainty.' },
  { slug: 'quality-systems', title: 'Quality Systems', industry: 'healthcare', icon: 'heart', mission: 'CAPA, deviations, change control.' },
  { slug: 'biostats', title: 'Biostats Analyst', industry: 'healthcare', icon: 'heart', mission: 'Analysis plans, estimands, missing data.' },
  { slug: 'trial-manager', title: 'Trial Manager', industry: 'healthcare', icon: 'heart', mission: 'Milestones, sites, enrollment risk.' },
  { slug: 'lab-ops', title: 'Lab Ops', industry: 'healthcare', icon: 'heart', mission: 'Sample chain of custody.' },
  { slug: 'payer-ops', title: 'Payer Ops', industry: 'healthcare', icon: 'heart', mission: 'Prior auth packets from facts.' },
  { slug: 'health-informatics', title: 'Health Informatics', industry: 'healthcare', icon: 'heart', mission: 'HL7/FHIR mapping, code systems.' },
  { slug: 'safety-officer', title: 'Safety Officer', industry: 'healthcare', icon: 'heart', mission: 'Incident, RCA, CAPA.' },
  { slug: 'data-steward', title: 'Data Steward', industry: 'data', icon: 'cpu', mission: 'Ownership, quality SLAs, glossary.' },
  { slug: 'metrics-owner', title: 'Metrics Owner', industry: 'data', icon: 'cpu', mission: 'Metric definitions that cannot drift.' },
  { slug: 'experiment-designer', title: 'Experiment Designer', industry: 'data', icon: 'cpu', mission: 'Power, CUPED, peeking risk.' },
  { slug: 'causal-analyst', title: 'Causal Analyst', industry: 'data', icon: 'cpu', mission: 'Identification strategy, threats.' },
  { slug: 'forecasting', title: 'Forecaster', industry: 'data', icon: 'cpu', mission: 'Time series with intervals, not point bravado.' },
  { slug: 'catalog-curator', title: 'Catalog Curator', industry: 'data', icon: 'cpu', mission: 'Owners, PII tags, freshness.' },
  { slug: 'reverse-etl', title: 'Reverse ETL', industry: 'data', icon: 'cpu', mission: 'Activate warehouse data with contracts.' },
  { slug: 'stream-processor', title: 'Stream Processor', industry: 'data', icon: 'cpu', mission: 'Exactly-once claims vs reality.' },
  { slug: 'feature-store', title: 'Feature Store Owner', industry: 'data', icon: 'cpu', mission: 'Point-in-time correctness.' },
  { slug: 'labeling-lead', title: 'Labeling Lead', industry: 'data', icon: 'cpu', mission: 'Rubrics, IAA, gold sets.' },
  { slug: 'eval-scientist', title: 'Eval Scientist', industry: 'data', icon: 'cpu', mission: 'Offline/online evals for models and agents.' },
  { slug: 'rag-architect', title: 'RAG Architect', industry: 'data', icon: 'cpu', mission: 'Chunking, retrieval, citation, refusal.' },
  { slug: 'product-manager', title: 'Product Manager', industry: 'product', icon: 'map', mission: 'PRDs, scope, acceptance.' },
  { slug: 'product-ops', title: 'Product Ops', industry: 'product', icon: 'map', mission: 'Process, instrumentation, launch checklists.' },
  { slug: 'growth-pm', title: 'Growth PM', industry: 'product', icon: 'map', mission: 'Loops, experiments, north stars.' },
  { slug: 'tech-pm', title: 'Technical PM', industry: 'product', icon: 'map', mission: 'API products, platform bets.' },
  { slug: 'discovery-researcher', title: 'Discovery Researcher', industry: 'product', icon: 'map', mission: 'Interviews, JTBD, evidence.' },
  { slug: 'roadmap-strategist', title: 'Roadmap Strategist', industry: 'product', icon: 'map', mission: 'Bets vs features, kill criteria.' },
  { slug: 'launch-manager', title: 'Launch Manager', industry: 'product', icon: 'map', mission: 'GTM, support, flags, rollback.' },
  { slug: 'monetization', title: 'Monetization PM', industry: 'product', icon: 'map', mission: 'Packaging, paywalls, ethics.' },
  { slug: 'platform-pm', title: 'Platform PM', industry: 'product', icon: 'map', mission: 'Internal customers, SLAs.' },
  { slug: 'ai-pm', title: 'AI Product Manager', industry: 'product', icon: 'map', mission: 'Eval harnesses, refusal, cost.' },
  { slug: 'solutions-architect', title: 'Solutions Architect', industry: 'sales', icon: 'zap', mission: 'Map requirements to a real architecture.' },
  { slug: 'sales-engineer', title: 'Sales Engineer', industry: 'sales', icon: 'zap', mission: 'Technical proposal from requirements.' },
  { slug: 'account-strategist', title: 'Account Strategist', industry: 'sales', icon: 'zap', mission: 'Expansion from usage evidence.' },
  { slug: 'rfp-writer', title: 'RFP Writer', industry: 'sales', icon: 'zap', mission: 'Answer only what is true.' },
  { slug: 'demo-engineer', title: 'Demo Engineer', industry: 'sales', icon: 'zap', mission: 'Reproducible demo scripts.' },
  { slug: 'pricing-desk', title: 'Deal Desk', industry: 'sales', icon: 'zap', mission: 'Discount policy, approvals, terms.' },
  { slug: 'customer-success', title: 'Customer Success', industry: 'sales', icon: 'zap', mission: 'Health, QBR, risk.' },
  { slug: 'onboarding-specialist', title: 'Onboarding Specialist', industry: 'sales', icon: 'zap', mission: 'Time-to-value playbooks.' },
  { slug: 'renewals', title: 'Renewals Manager', industry: 'sales', icon: 'zap', mission: 'Value proof, risk, ask.' },
  { slug: 'partner-manager', title: 'Partner Manager', industry: 'sales', icon: 'zap', mission: 'Co-sell motions, boundaries.' },
  { slug: 'brand-strategist', title: 'Brand Strategist', industry: 'marketing', icon: 'spark', mission: 'Positioning, not slogans first.' },
  { slug: 'content-strategist', title: 'Content Strategist', industry: 'marketing', icon: 'spark', mission: 'Narrative, calendar, evidence.' },
  { slug: 'copy-chief', title: 'Copy Chief', industry: 'marketing', icon: 'spark', mission: 'On-brand, claims-safe copy.' },
  { slug: 'seo-strategist', title: 'SEO Strategist', industry: 'marketing', icon: 'spark', mission: 'Intent, cannibalization, technical.' },
  { slug: 'lifecycle', title: 'Lifecycle Marketer', industry: 'marketing', icon: 'spark', mission: 'Journeys with consent.' },
  { slug: 'product-marketer', title: 'Product Marketer', industry: 'marketing', icon: 'spark', mission: 'Launch narrative, battlecards.' },
  { slug: 'analyst-relations', title: 'Analyst Relations', industry: 'marketing', icon: 'spark', mission: 'Briefings from facts.' },
  { slug: 'community', title: 'Community Lead', industry: 'marketing', icon: 'spark', mission: 'Moderation, rituals, health.' },
  { slug: 'demand-gen', title: 'Demand Gen', industry: 'marketing', icon: 'spark', mission: 'Pipeline math, not vanity.' },
  { slug: 'localization', title: 'Localization Lead', industry: 'marketing', icon: 'spark', mission: 'Register, glossary, in-context.' },
  { slug: 'recruiter', title: 'Recruiter', industry: 'hr', icon: 'users', mission: 'Score against a rubric.' },
  { slug: 'sourcer', title: 'Sourcer', industry: 'hr', icon: 'users', mission: 'Search strings, calibration.' },
  { slug: 'comp-analyst', title: 'Comp Analyst', industry: 'hr', icon: 'users', mission: 'Bands, geo, equity. Not advice.' },
  { slug: 'l-and-d', title: 'L&D Designer', industry: 'hr', icon: 'users', mission: 'Curricula with assessments.' },
  { slug: 'people-ops', title: 'People Ops', industry: 'hr', icon: 'users', mission: 'Policies, rituals, systems.' },
  { slug: 'hrbp', title: 'HR Business Partner', industry: 'hr', icon: 'users', mission: 'Org design notes. Not advice.' },
  { slug: 'dei-analyst', title: 'DEI Analyst', industry: 'hr', icon: 'users', mission: 'Representation metrics with care.' },
  { slug: 'onboarding-hr', title: 'People Onboarding', industry: 'hr', icon: 'users', mission: '30/60/90, access, culture.' },
  { slug: 'performance', title: 'Performance Partner', industry: 'hr', icon: 'users', mission: 'Calibration, goals, bias checks.' },
  { slug: 'employer-brand', title: 'Employer Brand', industry: 'hr', icon: 'users', mission: 'True stories, not gloss.' },
  { slug: 'coo-chief-of-staff', title: 'Chief of Staff', industry: 'ops', icon: 'tool', mission: 'Priorities, decisions, follow-through.' },
  { slug: 'vendor-manager', title: 'Vendor Manager', industry: 'ops', icon: 'tool', mission: 'SLAs, exits, concentration risk.' },
  { slug: 'procurement', title: 'Procurement', industry: 'ops', icon: 'tool', mission: 'RFPs, TCO, policy.' },
  { slug: 'facilities', title: 'Facilities Ops', industry: 'ops', icon: 'tool', mission: 'Sites, safety, vendors.' },
  { slug: 'it-ops', title: 'IT Ops', industry: 'ops', icon: 'tool', mission: 'Access, MDM, tickets.' },
  { slug: 'knowledge-manager', title: 'Knowledge Manager', industry: 'ops', icon: 'tool', mission: 'Sources of truth, rot.' },
  { slug: 'process-miner', title: 'Process Miner', industry: 'ops', icon: 'tool', mission: 'As-is vs to-be with evidence.' },
  { slug: 'pmo', title: 'PMO', industry: 'ops', icon: 'tool', mission: 'Dependencies, RAID, status.' },
  { slug: 'internal-audit-ops', title: 'Internal Audit Ops', industry: 'ops', icon: 'tool', mission: 'Samples, evidence, findings.' },
  { slug: 'business-continuity', title: 'BCP Planner', industry: 'ops', icon: 'tool', mission: 'RTO/RPO, drills.' },
  { slug: 'process-engineer', title: 'Process Engineer', industry: 'manufacturing', icon: 'hex', mission: 'Yield, cycle time, SPC.' },
  { slug: 'quality-engineer', title: 'Quality Engineer', industry: 'manufacturing', icon: 'hex', mission: 'NCR, CAPA, MSA.' },
  { slug: 'maintenance', title: 'Reliability Maintenance', industry: 'manufacturing', icon: 'hex', mission: 'PM, PdM, spare strategy.' },
  { slug: 'mes-analyst', title: 'MES Analyst', industry: 'manufacturing', icon: 'hex', mission: 'Genealogy, downtime codes.' },
  { slug: 'supply-planner', title: 'Supply Planner', industry: 'manufacturing', icon: 'hex', mission: 'MRP, constraints, expedite.' },
  { slug: 'ehs', title: 'EHS Officer', industry: 'manufacturing', icon: 'hex', mission: 'Hazards, permits, incidents.' },
  { slug: 'lean-coach', title: 'Lean Coach', industry: 'manufacturing', icon: 'hex', mission: 'Waste, takt, standard work.' },
  { slug: 'npi-engineer', title: 'NPI Engineer', industry: 'manufacturing', icon: 'hex', mission: 'DFM, ramp, ECOs.' },
  { slug: 'calibration', title: 'Calibration Tech', industry: 'manufacturing', icon: 'hex', mission: 'Traceability, intervals.' },
  { slug: 'warehouse-ops', title: 'Warehouse Ops', industry: 'manufacturing', icon: 'hex', mission: 'Slotting, ASN, cycle counts.' },
  { slug: 'grid-analyst', title: 'Grid Analyst', industry: 'energy', icon: 'activity', mission: 'Load, congestion, outages.' },
  { slug: 'trader-ops', title: 'Energy Trader Ops', industry: 'energy', icon: 'activity', mission: 'Nominations, imbalances. No live trades.' },
  { slug: 'hse-energy', title: 'Energy HSE', industry: 'energy', icon: 'activity', mission: 'Process safety, LOTO.' },
  { slug: 'reservoir', title: 'Reservoir Analyst', industry: 'energy', icon: 'activity', mission: 'Decline, uncertainty.' },
  { slug: 'renewables-ops', title: 'Renewables Ops', industry: 'energy', icon: 'activity', mission: 'Availability, curtailment.' },
  { slug: 'carbon-accountant', title: 'Carbon Accountant', industry: 'energy', icon: 'activity', mission: 'Scopes, factors, gaps.' },
  { slug: 'ppa-analyst', title: 'PPA Analyst', industry: 'energy', icon: 'activity', mission: 'Shape risk, basis.' },
  { slug: 'scada-reviewer', title: 'SCADA Reviewer', industry: 'energy', icon: 'activity', mission: 'Tag hygiene, unsafe commands.' },
  { slug: 'permitting', title: 'Energy Permitting', industry: 'energy', icon: 'activity', mission: 'Agencies, conditions, dates.' },
  { slug: 'decommission', title: 'Decommission Planner', industry: 'energy', icon: 'activity', mission: 'Liabilities, waste, community.' },
  { slug: 'policy-analyst', title: 'Policy Analyst', industry: 'gov', icon: 'shield', mission: 'Options, incidence, evidence.' },
  { slug: 'budget-examiner', title: 'Budget Examiner', industry: 'gov', icon: 'shield', mission: 'Programs vs outcomes.' },
  { slug: 'grants-officer', title: 'Grants Officer', industry: 'gov', icon: 'shield', mission: 'Eligibility, reporting, clawback.' },
  { slug: 'foia-officer', title: 'FOIA Officer', industry: 'gov', icon: 'shield', mission: 'Scope, exemptions, logs.' },
  { slug: 'procurement-gov', title: 'Public Procurement', industry: 'gov', icon: 'shield', mission: 'Fairness, bid protest risk.' },
  { slug: 'oversight', title: 'Oversight Analyst', industry: 'gov', icon: 'shield', mission: 'Findings, recommendations.' },
  { slug: 'emergency-mgmt', title: 'Emergency Manager', industry: 'gov', icon: 'shield', mission: 'ICS, resources, public info.' },
  { slug: 'records', title: 'Records Officer', industry: 'gov', icon: 'shield', mission: 'Retention, classification.' },
  { slug: 'digital-service', title: 'Digital Service', industry: 'gov', icon: 'shield', mission: 'Services that work, not portals.' },
  { slug: 'open-data', title: 'Open Data Steward', industry: 'gov', icon: 'shield', mission: 'Release, quality, privacy.' },
  { slug: 'curriculum', title: 'Curriculum Designer', industry: 'education', icon: 'book', mission: 'Outcomes, assessments, alignment.' },
  { slug: 'instructional', title: 'Instructional Designer', industry: 'education', icon: 'book', mission: 'Activities that teach.' },
  { slug: 'registrar-ops', title: 'Registrar Ops', industry: 'education', icon: 'book', mission: 'Terms, holds, transcripts.' },
  { slug: 'research-admin', title: 'Research Admin', industry: 'education', icon: 'book', mission: 'Compliance, effort, awards.' },
  { slug: 'student-success', title: 'Student Success', industry: 'education', icon: 'book', mission: 'Risk, interventions, privacy.' },
  { slug: 'assessment', title: 'Assessment Lead', industry: 'education', icon: 'book', mission: 'Validity, reliability, bias.' },
  { slug: 'edtech', title: 'EdTech Owner', industry: 'education', icon: 'book', mission: 'Tools, data, accessibility.' },
  { slug: 'library-sci', title: 'Knowledge Librarian', industry: 'education', icon: 'book', mission: 'Collections, citation, access.' },
  { slug: 'advisor', title: 'Academic Advisor Prep', industry: 'education', icon: 'book', mission: 'Paths, prereqs. Not counseling.' },
  { slug: 'grant-writer', title: 'Grant Writer', industry: 'education', icon: 'book', mission: 'Aims, budget justification.' },
  { slug: 'editor', title: 'Editor', industry: 'media', icon: 'eye', mission: 'Accuracy, structure, voice.' },
  { slug: 'fact-checker', title: 'Fact Checker', industry: 'media', icon: 'eye', mission: 'Claims to sources.' },
  { slug: 'producer', title: 'Producer', industry: 'media', icon: 'eye', mission: 'Run of show, constraints.' },
  { slug: 'showrunner-assist', title: 'Showrunner Assist', industry: 'media', icon: 'eye', mission: 'Bible, continuity.' },
  { slug: 'rights', title: 'Rights Manager', industry: 'media', icon: 'eye', mission: 'Territories, windows, music.' },
  { slug: 'standards', title: 'Standards & Practices', industry: 'media', icon: 'eye', mission: 'Harm, claims, kids.' },
  { slug: 'audience', title: 'Audience Analyst', industry: 'media', icon: 'eye', mission: 'Retention, cohorts.' },
  { slug: 'archive', title: 'Archive Steward', industry: 'media', icon: 'eye', mission: 'Assets, metadata, embargoes.' },
  { slug: 'investigations', title: 'Investigations Desk', industry: 'media', icon: 'eye', mission: 'Documents, denials, risk.' },
  { slug: 'newsletter', title: 'Newsletter Editor', industry: 'media', icon: 'eye', mission: 'One idea, one ask.' },
  { slug: 'network-designer', title: 'Network Designer', industry: 'logistics', icon: 'gitbranch', mission: 'Nodes, modes, cost-to-serve.' },
  { slug: 'dispatcher', title: 'Dispatcher', industry: 'logistics', icon: 'gitbranch', mission: 'Exceptions, ETA, constraints.' },
  { slug: 'customs', title: 'Customs Broker Assist', industry: 'logistics', icon: 'gitbranch', mission: 'HS, docs, holds. Not advice.' },
  { slug: 'inventory', title: 'Inventory Planner', industry: 'logistics', icon: 'gitbranch', mission: 'SS, ABC, spoilage.' },
  { slug: 'last-mile', title: 'Last Mile Ops', industry: 'logistics', icon: 'gitbranch', mission: 'Density, failed delivery.' },
  { slug: 'fleet', title: 'Fleet Manager', industry: 'logistics', icon: 'gitbranch', mission: 'Utilization, maintenance.' },
  { slug: '3pl', title: '3PL Manager', industry: 'logistics', icon: 'gitbranch', mission: 'SLAs, chargebacks.' },
  { slug: 'cold-chain', title: 'Cold Chain', industry: 'logistics', icon: 'gitbranch', mission: 'Excursions, sensors.' },
  { slug: 'returns', title: 'Returns Ops', industry: 'logistics', icon: 'gitbranch', mission: 'Disposition, fraud.' },
  { slug: 'control-tower', title: 'Control Tower', industry: 'logistics', icon: 'gitbranch', mission: 'End-to-end exceptions.' },
  { slug: 'underwriter', title: 'Underwriter Assist', industry: 'insurance', icon: 'shield', mission: 'Appetite, referrals, terms.' },
  { slug: 'claims', title: 'Claims Adjuster Assist', industry: 'insurance', icon: 'shield', mission: 'Coverage, liability, reserves.' },
  { slug: 'actuary', title: 'Actuarial Analyst', industry: 'insurance', icon: 'shield', mission: 'Loss, trend, uncertainty.' },
  { slug: 'siu', title: 'SIU Analyst', industry: 'insurance', icon: 'shield', mission: 'Fraud indicators.' },
  { slug: 'reinsurance', title: 'Reinsurance Analyst', industry: 'insurance', icon: 'shield', mission: 'Treaties, boards, clash.' },
  { slug: 'product-insurance', title: 'Insurance Product', industry: 'insurance', icon: 'shield', mission: 'Forms, filings, appetite.' },
  { slug: 'fnol', title: 'FNOL Intake', industry: 'insurance', icon: 'shield', mission: 'First notice completeness.' },
  { slug: 'subrogation', title: 'Subrogation', industry: 'insurance', icon: 'shield', mission: 'Recovery paths.' },
  { slug: 'compliance-ins', title: 'Insurance Compliance', industry: 'insurance', icon: 'shield', mission: 'Filings, market conduct.' },
  { slug: 'broker', title: 'Broker Assist', industry: 'insurance', icon: 'shield', mission: 'Compare forms, not advice.' },
  { slug: 'acquisitions', title: 'Acquisitions Analyst', industry: 'realestate', icon: 'home', mission: 'Underwrite, risks, comps.' },
  { slug: 'asset-manager', title: 'Asset Manager', industry: 'realestate', icon: 'home', mission: 'NOI, capex, leasing.' },
  { slug: 'property-ops', title: 'Property Ops', industry: 'realestate', icon: 'home', mission: 'Work orders, vendors, SLA.' },
  { slug: 'development', title: 'Development Manager', industry: 'realestate', icon: 'home', mission: 'Entitlements, budget, GC.' },
  { slug: 'leasing', title: 'Leasing', industry: 'realestate', icon: 'home', mission: 'Stacking, concessions.' },
  { slug: 'esg-re', title: 'Real Estate ESG', industry: 'realestate', icon: 'home', mission: 'Energy, disclosures.' },
  { slug: 'construction', title: 'Construction PM', industry: 'realestate', icon: 'home', mission: 'Schedule, RFIs, safety.' },
  { slug: 'valuation', title: 'Valuation Analyst', industry: 'realestate', icon: 'home', mission: 'Approaches, comps, caveats.' },
  { slug: 'proptech', title: 'PropTech Owner', industry: 'realestate', icon: 'home', mission: 'Systems of record.' },
  { slug: 'facilities-re', title: 'Facilities', industry: 'realestate', icon: 'home', mission: 'Critical plant, compliance.' },
  { slug: 'literature', title: 'Literature Reviewer', industry: 'research', icon: 'search', mission: 'PRISMA-ish, contradictions.' },
  { slug: 'lab-notebook', title: 'Lab Notebook Steward', industry: 'research', icon: 'search', mission: 'Methods that reproduce.' },
  { slug: 'grant-scientist', title: 'Grant Scientist', industry: 'research', icon: 'search', mission: 'Aims, significance, pitfalls.' },
  { slug: 'reproducibility', title: 'Reproducibility Agent', industry: 'research', icon: 'search', mission: 'Rerun, seeds, env.' },
  { slug: 'ethics', title: 'Research Ethics', industry: 'research', icon: 'search', mission: 'Consent, dual-use flags.' },
  { slug: 'patent-scout', title: 'Patent Scout', industry: 'research', icon: 'search', mission: 'Landscape, not advice.' },
  { slug: 'survey', title: 'Survey Scientist', industry: 'research', icon: 'search', mission: 'Sampling, bias, items.' },
  { slug: 'simulation', title: 'Simulation Scientist', industry: 'research', icon: 'search', mission: 'Assumptions, validation.' },
  { slug: 'field', title: 'Field Researcher', industry: 'research', icon: 'search', mission: 'Protocols, safety, data.' },
  { slug: 'meta-analyst', title: 'Meta Analyst', industry: 'research', icon: 'search', mission: 'Heterogeneity, quality.' },
  { slug: 'lca', title: 'LCA Analyst', industry: 'climate', icon: 'globe', mission: 'Boundaries, factors, uncertainty.' },
  { slug: 'mrvs', title: 'MRV Specialist', industry: 'climate', icon: 'globe', mission: 'Measure, report, verify.' },
  { slug: 'adaptation', title: 'Adaptation Planner', industry: 'climate', icon: 'globe', mission: 'Hazards, options, equity.' },
  { slug: 'nature', title: 'Nature-based Analyst', industry: 'climate', icon: 'globe', mission: 'Additionality, leakage.' },
  { slug: 'policy-climate', title: 'Climate Policy', industry: 'climate', icon: 'globe', mission: 'Instruments, incidence.' },
  { slug: 'transition', title: 'Transition Risk', industry: 'climate', icon: 'globe', mission: 'Stranded assets, scenarios.' },
  { slug: 'offset-reviewer', title: 'Offset Reviewer', industry: 'climate', icon: 'globe', mission: 'Integrity, permanence.' },
  { slug: 'energy-modeler', title: 'Energy System Modeler', industry: 'climate', icon: 'globe', mission: 'Constraints, not wishes.' },
  { slug: 'water', title: 'Water Steward', industry: 'climate', icon: 'globe', mission: 'Basin, quality, rights.' },
  { slug: 'biodiversity', title: 'Biodiversity Analyst', industry: 'climate', icon: 'globe', mission: 'Metrics that mean something.' },
  { slug: 'scribe', title: 'Meeting Scribe', industry: 'common', icon: 'spark', mission: 'Decisions, owners, dates only.' },
  { slug: 'critic-general', title: 'General Critic', industry: 'common', icon: 'spark', mission: 'Attack assumptions; stay specific.' },
  { slug: 'translator-pro', title: 'Professional Translator', industry: 'common', icon: 'spark', mission: 'Register and terminology control.' },
  { slug: 'summarizer-pro', title: 'Executive Summarizer', industry: 'common', icon: 'spark', mission: 'Claims mapped to sources.' },
  { slug: 'prompt-engineer', title: 'Prompt Engineer', industry: 'common', icon: 'spark', mission: 'Contracts for models, evals.' },
  { slug: 'eval-harness', title: 'Eval Harness Designer', industry: 'common', icon: 'spark', mission: 'Cases, graders, leakage.' },
  { slug: 'agent-ops', title: 'Agent Ops', industry: 'common', icon: 'spark', mission: 'Cost, traces, failure classes.' },
  { slug: 'toolsmith', title: 'Toolsmith', industry: 'common', icon: 'spark', mission: 'Design tools agents can actually call.' },
  { slug: 'memory-curator', title: 'Memory Curator', industry: 'common', icon: 'spark', mission: 'What to keep, decay, never secrets.' },
  { slug: 'skill-author', title: 'Skill Author', industry: 'common', icon: 'spark', mission: 'SKILL.md that a Hermes agent can run.' },
  { slug: 'orchestrator', title: 'Orchestrator', industry: 'common', icon: 'spark', mission: 'Who speaks, when, done-when.' },
  { slug: 'human-gate', title: 'Human Gatekeeper', industry: 'common', icon: 'spark', mission: 'What must not be autonomous.' },
  { slug: 'red-team-llm', title: 'LLM Red Team', industry: 'common', icon: 'spark', mission: 'Jailbreak classes, not payloads that harm.' },
  { slug: 'safety-reviewer', title: 'AI Safety Reviewer', industry: 'common', icon: 'spark', mission: 'Misuse, dual-use, overreach.' },
  { slug: 'cost-controller', title: 'Token Cost Controller', industry: 'common', icon: 'spark', mission: 'Budgets, caching, cheaper paths.' },
  { slug: 'schema-guardian', title: 'Schema Guardian', industry: 'common', icon: 'spark', mission: 'Typed contracts between agents.' },
  { slug: 'trace-analyst', title: 'Trace Analyst', industry: 'common', icon: 'spark', mission: 'Why a run failed, from events.' },
  { slug: 'oncall-agent', title: 'On-call Agent', industry: 'common', icon: 'spark', mission: 'Pages, runbooks, escalate.' },
  { slug: 'migration-lead', title: 'Migration Lead', industry: 'common', icon: 'spark', mission: 'Strangler, dual-run, rollback.' },
  { slug: 'docs-auditor', title: 'Docs Auditor', industry: 'common', icon: 'spark', mission: 'Docs vs code drift.' },
];

export const INDUSTRIES = Array.from(new Set(ROLE_PACKS.map((p) => p.industry)));
export const ROLE_PACK_COUNT = ROLE_PACKS.length;
