import { createRequire as __mjCreateRequire } from "node:module"; const require = __mjCreateRequire(import.meta.url);

// probe/agentsMd.test.ts
import * as fs from "node:fs";
import * as os from "node:os";
import * as path2 from "node:path";

// src/mission/agentsMd.ts
import * as fsSync from "node:fs";
import * as path from "node:path";
function parseAgentsMd(raw, file) {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const sections = [];
  let current = { heading: null, lines: [] };
  for (const line of lines) {
    const h = line.match(/^(#{1,3})\s+(.+)$/);
    if (h) {
      if (current.heading !== null || current.lines.some((l) => l.trim())) sections.push(current);
      current = { heading: h[2].trim(), lines: [] };
    } else {
      current.lines.push(line);
    }
  }
  if (current.heading !== null || current.lines.some((l) => l.trim())) sections.push(current);
  const title = sections.find((s) => s.heading !== null)?.heading ?? path.basename(file);
  return { file, title, sections, raw };
}
function collectAgentsContext(root, maxDepth = 3) {
  const docs = [];
  const walk = (dir2, depth, rel) => {
    if (depth > maxDepth) return;
    const file = path.join(dir2, "AGENTS.md");
    try {
      if (fsSync.statSync(file).isFile()) {
        docs.push(parseAgentsMd(fsSync.readFileSync(file, "utf8"), rel ? `${rel}/AGENTS.md` : "AGENTS.md"));
      }
    } catch {
    }
    if (depth === maxDepth) return;
    let entries;
    try {
      entries = fsSync.readdirSync(dir2, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.isDirectory() && !e.name.startsWith(".") && e.name !== "node_modules" && e.name !== "target") {
        walk(path.join(dir2, e.name), depth + 1, rel ? `${rel}/${e.name}` : e.name);
      }
    }
  };
  walk(root, 0, "");
  const composed = docs.map((d) => `### from ${d.file}
${d.raw.trim()}`).join("\n\n");
  return { docs, composed };
}
function agentsMdForMission(m) {
  const lines = [];
  lines.push(`# ${m.objective}`);
  lines.push("");
  lines.push("<!-- generated by VH for mission ");
  lines.push(`${m.missionId} --`);
  lines.push("");
  lines.push("## Context");
  lines.push("");
  lines.push(`This workspace is being worked on by VH mission \`${m.missionId}\`.`);
  lines.push("Follow the instructions in this file. They are the contract for every agent in this mission.");
  lines.push("");
  lines.push("## Done when");
  lines.push("");
  for (const d of m.doneWhen) lines.push(`- ${d}`);
  lines.push("");
  lines.push("## Boundaries");
  lines.push("");
  for (const b of m.boundaries) lines.push(`- ${b}`);
  lines.push("");
  lines.push("## Tasks");
  lines.push("");
  for (const t of m.tasks) {
    const via = t.harness ? ` (via ${t.harness})` : "";
    lines.push(`### ${t.title}${via}`);
    lines.push(`- kind: ${t.kind}`);
    if (t.checks.length > 0) {
      lines.push(`- verify with: ${t.checks.map((c) => `\`${c}\``).join(", ")}`);
    }
    lines.push("");
  }
  lines.push("## Ground rules");
  lines.push("");
  lines.push("- Never invent tools, APIs, or secrets. Mark unknowns as unknown.");
  lines.push("- Run the verification commands before claiming a task is done.");
  lines.push("- Leave the workspace in a state where those commands pass.");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("This file is regenerated by VH on plan changes. Edit freely \u2014 your edits are read by the next seat that starts.");
  lines.push("");
  return lines.join("\n");
}
function writeAgentsMd(root, m) {
  const file = path.join(root, "AGENTS.md");
  fsSync.mkdirSync(root, { recursive: true });
  fsSync.writeFileSync(file, agentsMdForMission(m), "utf8");
  return file;
}

// probe/agentsMd.test.ts
var passed = 0;
var failed = 0;
var failures = [];
function ok(label, cond, detail = "") {
  if (cond) {
    passed += 1;
    console.log(`  ok   ${label}`);
  } else {
    failed += 1;
    failures.push(`${label}${detail ? ` \u2014 ${detail}` : ""}`);
    console.log(`  FAIL ${label}${detail ? ` \u2014 ${detail}` : ""}`);
  }
}
function section(name) {
  console.log(`
== ${name}`);
}
var dir = fs.mkdtempSync(path2.join(os.tmpdir(), "mj-agentsmd-"));
try {
  section("0. reading: nearest-wins collection");
  fs.writeFileSync(
    path2.join(dir, "AGENTS.md"),
    "# Project\n\n- Build with `npm ci && npm run build`\n- Never touch `/infra`\n",
    "utf8"
  );
  fs.mkdirSync(path2.join(dir, "packages", "web"), { recursive: true });
  fs.writeFileSync(
    path2.join(dir, "packages", "web", "AGENTS.md"),
    "# Web package\n\n- Tests: `npm test -w web`\n",
    "utf8"
  );
  fs.mkdirSync(path2.join(dir, "packages", "web", "deep", "deeper"), { recursive: true });
  fs.writeFileSync(path2.join(dir, "packages", "web", "deep", "deeper", "AGENTS.md"), "# Too deep\n", "utf8");
  const ctx = collectAgentsContext(dir, 3);
  ok("the root AGENTS.md is found", ctx.docs.some((d) => d.file === "AGENTS.md"));
  ok("a nested AGENTS.md is found", ctx.docs.some((d) => d.file === "packages/web/AGENTS.md"));
  ok("collection is depth-capped", !ctx.docs.some((d) => d.file.includes("deep")), ctx.docs.map((d) => d.file).join(", "));
  ok("the composed block carries both files", ctx.composed.includes("npm run build") && ctx.composed.includes("npm test -w web"));
  ok("provenance is explicit per block", ctx.composed.includes("### from packages/web/AGENTS.md"));
  section("1. parsing: sections survive any reasonable markdown");
  const parsed = parseAgentsMd("# T\n\nintro line\n\n## Build\n\nnpm ci\nnpm test\n", "AGENTS.md");
  ok("intro lines survive under the title section", parsed.sections[0].heading === "T" && parsed.sections[0].lines.join(" ").includes("intro"), JSON.stringify(parsed.sections[0]));
  ok("named sections are captured in order", parsed.sections[1].heading === "Build" && parsed.sections[1].lines.includes("npm test"));
  ok("the title falls back sensibly", parsed.title === "T");
  section("2. writing: a mission renders a valid AGENTS.md");
  const ws = path2.join(dir, "mission-workspace");
  const written = writeAgentsMd(ws, {
    missionId: "m-probe-1",
    objective: "Fix the flaky checkout tests",
    doneWhen: ["npm test exits 0 twice in a row", "no test is skipped"],
    boundaries: ["write only inside /src/checkout", "never run git push"],
    tasks: [
      { title: "Reproduce the flake", kind: "investigate", checks: ["npm test -- --repeat 5"], harness: "acp" },
      { title: "Fix it", kind: "implement", checks: ["npm test"] }
    ]
  });
  ok("the file is written into the workspace", fs.existsSync(written) && written.endsWith("AGENTS.md"));
  const text = fs.readFileSync(written, "utf8");
  ok("the objective is the title", text.startsWith("# Fix the flaky checkout tests"));
  ok("the done-when contract is present", text.includes("- npm test exits 0 twice in a row"));
  ok("boundaries are stated as instructions", text.includes("never run git push"));
  ok("per-task verify commands survive", text.includes("`npm test -- --repeat 5`"));
  ok("provenance names the mission", text.includes("m-probe-1"));
  section("3. the round-trip: VH reads back what VH wrote");
  const reread = collectAgentsContext(ws);
  ok("the generated file is discoverable", reread.docs.length === 1);
  ok("the generated file parses into sections", reread.docs[0].sections.length >= 4, `${reread.docs[0].sections.length} sections`);
  ok("and a different mission could consume it as context", reread.composed.includes("Fix the flaky checkout tests"));
  section("4. the missing-file case is quiet, not an error");
  const empty = collectAgentsContext(path2.join(dir, "no-such-dir"));
  ok("no docs, no throw", empty.docs.length === 0 && empty.composed === "");
  section("5. the generator is deterministic");
  const input = {
    missionId: "m-det",
    objective: "o",
    doneWhen: ["d"],
    boundaries: ["b"],
    tasks: [{ title: "t", kind: "implement", checks: ["c"] }]
  };
  ok("identical input, identical markdown", agentsMdForMission(input) === agentsMdForMission(input));
} finally {
  fs.rmSync(dir, { recursive: true, force: true });
}
console.log(`
${passed} passed, ${failed} failed`);
if (failed > 0) {
  console.log("\nfailures:");
  for (const f of failures) console.log(`  - ${f}`);
  process.exit(1);
}
