import { createRequire as __mjCreateRequire } from "node:module"; const require = __mjCreateRequire(import.meta.url);

// src/mission/collaboration.ts
function branchSafe(s) {
  return s.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/\.{2,}/g, ".").replace(/^\.+|\.+$/g, "").replace(/^-+|-+$/g, "").slice(0, 40) || "seat";
}
function planWorktrees(team, opts) {
  const plans = [];
  const root = opts.repoRoot.replace(/\/+$/, "");
  const hasWriter = team.seats.some((s) => s.mayWrite);
  for (const seat2 of team.seats) {
    if (!seat2.mayWrite) {
      if (opts.deferReview && hasWriter) {
        const path2 = `${root}-si-review-${branchSafe(opts.missionSlug)}-${branchSafe(seat2.id)}`;
        plans.push({
          seatId: seat2.id,
          branch: "",
          path: path2,
          createArgv: [],
          removeArgv: [["worktree", "remove", "--force", path2]],
          shared: false,
          deferred: true,
          reason: `${seat2.role} is read-only, so it gets its own worktree on the REVIEW SNAPSHOT \u2014 the base plus every writer branch merged. Pointing it at the base checkout would have it review the tree as it was before the work happened, which is the bug this replaces.`
        });
        continue;
      }
      plans.push({
        seatId: seat2.id,
        branch: opts.baseBranch,
        path: root,
        createArgv: [],
        removeArgv: [],
        shared: true,
        deferred: false,
        reason: `${seat2.role} is read-only \u2014 giving a reviewer its own worktree would mean it would review a tree nobody is writing to. Read-only seats share the base checkout.`
      });
      continue;
    }
    const branch = `vh/${opts.missionSlug}/${branchSafe(seat2.id)}`;
    const path = `${root}-si-${branchSafe(opts.missionSlug)}-${branchSafe(seat2.id)}`;
    plans.push({
      seatId: seat2.id,
      branch,
      path,
      createArgv: [["worktree", "add", "-b", branch, path, opts.baseBranch]],
      removeArgv: [["worktree", "remove", "--force", path]],
      shared: false,
      deferred: false,
      reason: `${seat2.role} writes, so it gets its own worktree on ${branch}. Two agents in one working tree overwrite each other.`
    });
  }
  return plans;
}
var CONTEXT_PATHS = [
  { harness: "hermes", path: "AGENTS.md" }
];
function briefingContents(opts) {
  const constraintsList = opts.constraints && opts.constraints.length ? opts.constraints.map((c) => `- ${c}`).join("\n") : "- (none declared)";
  const doNotTouchList = opts.doNotTouch && opts.doNotTouch.length ? opts.doNotTouch.map((p) => `- ${p}`).join("\n") : "- (none declared)";
  return [
    `# MISSION BRIEFING \u2014 Generated by VH`,
    ``,
    `## Objective`,
    opts.objective,
    ``,
    `## Constraints`,
    constraintsList,
    ``,
    `## Off-limits files (Do not touch)`,
    doNotTouchList,
    ``,
    `## Collaboration Rules`,
    `- OTHER worktrees are active simultaneously. Work ONLY on files matching your task scope.`,
    `- Do not reformat unrelated code; clean diffs make peer reviews possible.`,
    opts.testCommand ? `- Verify command: \`${opts.testCommand.join(" ")}\`` : ""
  ].filter(Boolean).join("\n");
}
function writeContextFiles(team, opts) {
  const activeHarnesses = new Set(team.seats.map((s) => s.harness));
  const out = [];
  const seenPaths = /* @__PURE__ */ new Set();
  const body = briefingContents(opts);
  for (const entry of CONTEXT_PATHS) {
    if (activeHarnesses.has(entry.harness)) {
      if (seenPaths.has(entry.path)) continue;
      seenPaths.add(entry.path);
      out.push({
        path: entry.path,
        contents: body,
        forHarness: entry.harness
      });
    }
  }
  if (out.length === 0 && team.seats.length > 0) {
    out.push({
      path: "AGENTS.md",
      contents: body,
      forHarness: team.seats[0].harness
    });
  }
  return out;
}
function globsOverlap(a, b) {
  if (a === b) return true;
  const normA = a.replace(/\*\*/g, "*").replace(/\/+$/, "");
  const normB = b.replace(/\*\*/g, "*").replace(/\/+$/, "");
  if (normA.startsWith(normB.replace(/\*$/, "")) || normB.startsWith(normA.replace(/\*$/, ""))) return true;
  return false;
}
function findClaimConflicts(claims) {
  const out = [];
  for (let i = 0; i < claims.length; i += 1) {
    for (let j = i + 1; j < claims.length; j += 1) {
      const a = claims[i];
      const b = claims[j];
      if (!a || !b) continue;
      const symbols = a.symbols.filter((s) => b.symbols.includes(s));
      if (symbols.length) {
        out.push({
          a: a.seatId,
          b: b.seatId,
          severity: "symbol",
          on: symbols,
          overlap: symbols,
          detail: `Both claim symbols: ${symbols.join(", ")}.`,
          advice: `Both claim ${symbols.join(", ")}. Merging two edits to one symbol produces something that is clean-looking and semantically broken \u2014 sequence these seats into separate waves.`
        });
        continue;
      }
      const pathOverlap = a.paths.filter((pa) => b.paths.some((pb) => globsOverlap(pa, pb)));
      if (pathOverlap.length) {
        out.push({
          a: a.seatId,
          b: b.seatId,
          severity: "path",
          on: pathOverlap,
          overlap: pathOverlap,
          detail: `Paths overlap: ${pathOverlap.join(", ")}.`,
          advice: `Both claim overlapping paths: ${pathOverlap.join(", ")}. Serialise these seats if they modify the same regions.`
        });
      }
    }
  }
  return out;
}
function planVerification(team) {
  const verifiers = team.seats.filter((s) => s.role === "reviewer" || s.role === "security");
  const out = [];
  const writers = team.seats.filter((s) => s.mayWrite);
  if (writers.length === 0) {
    return [];
  }
  for (const w of writers) {
    const independent = verifiers.find((v) => v.harness !== w.harness);
    const chosen = independent ?? verifiers[0] ?? null;
    if (!chosen) {
      out.push({
        writerSeatId: w.id,
        verifierSeatId: "",
        verifierId: "",
        independent: false,
        producerHarness: w.harness,
        verifierHarness: void 0,
        reason: "Self-certification is not verification \u2014 this writer has no reviewer.",
        detail: `${w.id} has no verifier on this team. Nothing checks its work.`
      });
      continue;
    }
    const isIndep = chosen.harness !== w.harness;
    const reason = isIndep ? `${chosen.id} (${chosen.harness}) verifies ${w.id} (${w.harness}) \u2014 blind spots are not shared.` : `WARNING: ${chosen.id} verifies ${w.id}, but both are ${w.harness}. A single-vendor review is advisory, not as verification.`;
    out.push({
      writerSeatId: w.id,
      verifierSeatId: chosen.id,
      verifierId: chosen.id,
      independent: isIndep,
      producerHarness: w.harness,
      verifierHarness: chosen.harness,
      reason,
      detail: reason
    });
  }
  return out;
}
function planCollaboration(team, opts) {
  const worktrees = planWorktrees(team, opts);
  const contextFiles = writeContextFiles(team, {
    objective: opts.objective,
    constraints: opts.constraints ?? [],
    doNotTouch: opts.doNotTouch ?? [],
    testCommand: opts.testCommand
  });
  const conflicts = findClaimConflicts(opts.claims ?? []);
  const verification = planVerification(team);
  const byRole = (r) => team.seats.filter((s) => s.role === r).map((s) => s.id);
  const waves = [];
  const scheduled = /* @__PURE__ */ new Set();
  const push = (seats, why) => {
    const fresh = seats.filter((s) => !scheduled.has(s));
    if (!fresh.length) return;
    for (const s of fresh) scheduled.add(s);
    waves.push({ seats: fresh, why });
  };
  push(byRole("planner"), "Planning first: nothing should write before the approach exists.");
  push(byRole("architect"), "Architecture next, still read-only, so the writers inherit a design.");
  const conflicted = new Set(conflicts.flatMap((c) => [c.a, c.b]));
  const writers = team.seats.filter((s) => s.mayWrite).map((s) => s.id);
  if (writers.length > 0) {
    const parallelWriters = writers.filter((w) => !conflicted.has(w));
    if (parallelWriters.length > 0) {
      push(parallelWriters, "Implementation: separate worktrees, so parallel writers cannot overwrite each other.");
    }
    for (const s of writers.filter((w) => conflicted.has(w))) {
      push([s], "Sequenced alone: its claim overlaps another seat's, so running them together would produce a merge that looks clean and is semantically wrong.");
    }
  }
  push(byRole("tester"), "Testing, against the merged result \u2014 so it must follow the writers, never join them.");
  push([...byRole("reviewer"), ...byRole("security")], "Independent review and security verification.");
  push(byRole("synthesizer"), "Synthesis of findings.");
  for (const s of team.seats) {
    if (!scheduled.has(s.id)) {
      push([s.id], `${s.role} execution.`);
    }
  }
  const problems = [];
  if (conflicts.some((c) => c.severity === "symbol")) {
    problems.push(`${conflicts.filter((c) => c.severity === "symbol").length} symbol-level claim conflict(s). Resolve these before starting, not at merge time.`);
  }
  if (verification.some((v) => !v.independent)) {
    problems.push(`${verification.filter((v) => !v.independent).length} writing seat(s) have no independent verifier.`);
  }
  const writerHarnesses = new Set(team.seats.filter((s) => s.mayWrite).map((s) => s.harness));
  if (writerHarnesses.size > 1) {
    problems.push(`${writerHarnesses.size} different CLIs will write in parallel. That is the point, but it means ${writerHarnesses.size} sets of edits to reconcile \u2014 review the merge, not just the branches.`);
  }
  return { teamId: team.id, missionSlug: opts.missionSlug, worktrees, contextFiles, conflicts, verification, waves, problems };
}
function setupArgv(plan) {
  const out = [];
  for (const w of plan.worktrees) {
    if (w.shared || w.deferred) continue;
    for (const argv of w.createArgv) out.push(["git", ...argv]);
  }
  return out;
}
function teardownArgv(plan) {
  const out = [];
  for (const w of plan.worktrees) {
    if (w.shared) continue;
    for (const argv of w.removeArgv) out.push(["git", ...argv]);
  }
  out.push(["git", "worktree", "prune"]);
  return out;
}
function renderPlan(plan) {
  const lines = [];
  lines.push(`TEAM ${plan.teamId} \u2014 mission "${plan.missionSlug}"`);
  lines.push("");
  lines.push("execution waves:");
  plan.waves.forEach((w, i) => {
    lines.push(`  wave ${i + 1}: ${w.seats.join(", ")}`);
    lines.push(`    ${w.why}`);
  });
  lines.push("");
  lines.push("isolation:");
  for (const w of plan.worktrees) {
    const kind = w.shared ? "shared base" : w.deferred ? "review snapshot (deferred)" : "private worktree";
    lines.push(`  ${w.seatId.padEnd(12)} ${kind.padEnd(26)} ${w.branch || "(resolved at wave time)"}`);
    lines.push(`    ${w.path}`);
  }
  lines.push("");
  lines.push("briefings:");
  for (const f of plan.contextFiles) lines.push(`  ${f.path}  (read by ${f.forHarness})`);
  if (plan.verification.length) {
    lines.push("");
    lines.push("verification:");
    for (const v of plan.verification) lines.push(`  ${v.detail} (independent: ${v.independent ? "yes" : "no"})`);
  }
  if (plan.problems.length) {
    lines.push("");
    lines.push("before you start:");
    for (const p of plan.problems) lines.push(`  ! ${p}`);
  }
  return lines.join("\n");
}

// src/domain/harness.ts
var RETIRED_HARNESSES = /* @__PURE__ */ new Set([
  "claude",
  "codex",
  "opencode",
  "openclaude",
  "copilot",
  "cursor",
  "cursor-agent",
  "grok",
  "cline",
  "kilo",
  "aider",
  "gemini",
  "antigravity",
  "amp",
  "crush",
  "openhands",
  "goose",
  "qwen",
  "amazonq",
  "droid",
  "kimi",
  "auggie",
  "warp",
  "acp",
  "agent"
]);
function isRetiredHarness(id) {
  return RETIRED_HARNESSES.has(id);
}
var HARNESSES = [
  {
    id: "hermes",
    name: "Native agent (in-process)",
    bins: [],
    argv: [],
    install: "Nothing to install \u2014 the agent loop runs inside SelfImpulse on your own provider key (or a local Ollama).",
    notes: "The vendored act/observe/adjust loop. Every crew seat runs here, so every action carries one audited receipt format and the trust story has no third party in it.",
    source: "src/engine/hermesRuntime.ts"
  },
  {
    id: "llm",
    name: "Direct LLM (API / Ollama)",
    bins: [],
    argv: [],
    install: "Save a provider key in Settings \u2192 Providers, or run Ollama locally",
    notes: "Not an agent loop. Calls the chat API with the composed agent prompt \u2014 the direct seam under the native runner."
  }
];
var HARNESS_BY_ID = new Map(HARNESSES.map((h) => [h.id, h]));
var HARNESS_OPTIONS = HARNESSES.filter((h) => !isRetiredHarness(h.id)).map((h) => h.id);

// src/mission/agentCapabilities.ts
var AGENT_CAPABILITIES = {
  hermes: {
    id: "hermes",
    name: "Hermes Runtime",
    // 19.7.15: hermes is IN-PROCESS. It has no binary, is not a stdio child,
    // and takes no argv. These two lines used to describe a subprocess that
    // does not exist; every caller that read them was reasoning about a seat
    // that could not run.
    bins: [],
    install: "bundled with SelfImpulse; runs in-process (src/engine/hermesRuntime.ts) \u2014 no binary, no argv",
    prompt: { argv: [], confidence: "docs", source: "in-process runtime: no argv exists by construction" },
    json: null,
    readOnly: null,
    write: null,
    fullAuto: null,
    maxTurns: null,
    timeout: null,
    outputSchema: null,
    worktree: null,
    cwd: null,
    model: null,
    resume: null,
    sessionStart: null,
    noAutoUpdate: null,
    filters: null,
    cost: null,
    enforcedReadOnly: false,
    gotchas: ["No enforced sandbox, so a hermes seat must never be assigned HIGH or CRITICAL risk."]
  },
  llm: {
    id: "llm",
    name: "Direct LLM",
    bins: [],
    install: "no binary; VH calls the provider API directly",
    // In-process API call: there is no command line, and the empty argv says so
    // rather than a fake ["$PROMPT"] that would read as a spawnable command.
    prompt: { argv: [], confidence: "docs", source: "in-process API call: no argv exists by construction" },
    json: null,
    readOnly: null,
    write: null,
    fullAuto: null,
    maxTurns: null,
    timeout: null,
    outputSchema: null,
    worktree: null,
    cwd: null,
    model: null,
    resume: null,
    sessionStart: null,
    noAutoUpdate: null,
    filters: null,
    cost: null,
    enforcedReadOnly: false,
    gotchas: ["No filesystem access and no enforced sandbox. Useful for reasoning, useless for edits."]
  }
};
var EXECUTABLE_HARNESSES = Object.keys(AGENT_CAPABILITIES).filter(
  (id) => AGENT_CAPABILITIES[id].bins.length > 0
);

// src/mission/agentTeam.ts
var SCHEMA_VERSION = 1;
var seat = (id, role, harness, over = {}) => ({
  id,
  role,
  harness,
  model: null,
  mayWrite: role === "coder" || role === "debugger",
  maxRisk: role === "coder" || role === "debugger" ? "MEDIUM" : "LOW",
  timeoutSecs: 900,
  maxTurns: null,
  instructions: "",
  ...over
});
var PREBUILT_TEAMS = [
  {
    id: "team.balanced",
    name: "Balanced",
    description: "Plan, build, test, review. One vendor writes, a second reviews \u2014 so the review is not the author grading its own work.",
    schemaVersion: SCHEMA_VERSION,
    budgetUsd: null,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    revision: 1,
    seats: [
      seat("planner", "planner", "hermes", { mayWrite: false, maxRisk: "LOW", instructions: "Break the objective into steps small enough to verify individually." }),
      seat("architect", "architect", "hermes", { mayWrite: false, maxRisk: "LOW" }),
      seat("impl", "coder", "hermes", { mayWrite: true, maxRisk: "MEDIUM", instructions: "Implement the change. Touch only what the task requires." }),
      seat("synthesizer", "synthesizer", "hermes", { mayWrite: false, maxRisk: "LOW" }),
      seat("test", "tester", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Run the repository's own checks and report what failed." }),
      seat("reviewer", "reviewer", "llm", { mayWrite: false, maxRisk: "LOW", model: "reviewer-tier", instructions: "Review the diff. Say what is wrong, not what is fine. Run on a different model from the writer \u2014 a reviewer on the writer's own weights is not independent evidence." }),
      seat("security", "security", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Check for security vulnerabilities." })
    ]
  },
  {
    id: "team.adversarial",
    name: "Adversarial",
    description: "Deliberately independent reviewers. Every writer is reviewed by a different model, because agreement between two seats running the same weights is weaker evidence than agreement across models.",
    schemaVersion: SCHEMA_VERSION,
    budgetUsd: null,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    revision: 1,
    seats: [
      seat("planner", "planner", "hermes", { mayWrite: false, maxRisk: "LOW" }),
      seat("impl", "coder", "hermes", { mayWrite: true, maxRisk: "MEDIUM" }),
      seat("test", "tester", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Prove the change works or find the case where it does not." }),
      seat("reviewer", "reviewer", "llm", { mayWrite: false, maxRisk: "LOW", model: "reviewer-tier", instructions: "Review independently, on a different model from the writer." }),
      seat("security", "security", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Look only for injection, secret leakage and unsafe deserialisation." }),
      seat("synthesizer", "synthesizer", "hermes", { mayWrite: false, maxRisk: "LOW", instructions: "Reconcile the verdicts into one decision." })
    ]
  },
  {
    id: "team.powerhouse",
    name: "Cross-Vendor Powerhouse",
    description: "One governed crew, every seat on the native in-process runtime: plans, architects, builds, debugs, tests, reviews and synthesizes \u2014 each seat pointed at its own model, each action receipted through the same gate.",
    schemaVersion: SCHEMA_VERSION,
    budgetUsd: null,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    revision: 1,
    seats: [
      seat("planner", "planner", "hermes", { mayWrite: false, maxRisk: "LOW", instructions: "Formulate the execution plan and criteria." }),
      seat("architect", "architect", "hermes", { mayWrite: false, maxRisk: "LOW", instructions: "Design component interfaces and data schemas." }),
      seat("coder", "coder", "hermes", { mayWrite: true, maxRisk: "MEDIUM", instructions: "Implement core logic and tests in isolated worktree." }),
      seat("debugger", "debugger", "hermes", { mayWrite: true, maxRisk: "MEDIUM", instructions: "Diagnose edge cases and optimize performance." }),
      seat("tester", "tester", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Run test suites and fuzz edge cases." }),
      seat("reviewer", "reviewer", "llm", { mayWrite: false, maxRisk: "LOW", instructions: "Conduct independent peer review against the snapshot merge." }),
      seat("synthesizer", "synthesizer", "hermes", { mayWrite: false, maxRisk: "LOW", instructions: "Reconcile findings into final release notes." })
    ]
  },
  {
    id: "team.solo",
    name: "Solo",
    description: "One seat. Cheap, fast, and the review is advisory only \u2014 an author grading its own work is not a review.",
    schemaVersion: SCHEMA_VERSION,
    budgetUsd: null,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    revision: 1,
    seats: [seat("impl", "coder", "hermes", { mayWrite: true, maxRisk: "MEDIUM", instructions: "Implement and self-check." })]
  },
  {
    id: "team.audit",
    name: "Read-only audit",
    description: "No seat may write. For answering 'what is wrong with this code?' without risking a change.",
    schemaVersion: SCHEMA_VERSION,
    budgetUsd: null,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    revision: 1,
    seats: [
      seat("reviewer", "reviewer", "llm", { mayWrite: false, maxRisk: "LOW", model: "reviewer-tier", instructions: "Review independently, on a different model from the writer." }),
      seat("security", "security", "llm", { mayWrite: false, maxRisk: "LOW" })
    ]
  }
];
var TEAM_BY_ID = new Map(PREBUILT_TEAMS.map((t) => [t.id, t]));

// probe/collaboration.test.ts
var pass = 0;
var fail = 0;
var ok = (c, m) => {
  if (c) pass += 1;
  else {
    fail += 1;
    console.log(`  FAIL ${m}`);
  }
};
var balanced = PREBUILT_TEAMS.find((t) => t.id === "team.balanced");
var adversarial = PREBUILT_TEAMS.find((t) => t.id === "team.adversarial");
var audit = PREBUILT_TEAMS.find((t) => t.id === "team.audit");
var REPO = { repoRoot: "/repo/app", baseBranch: "main", missionSlug: "rate-limiter" };
console.log("\n== 1. worktree isolation ==\n");
{
  const plans = planWorktrees(balanced, REPO);
  ok(plans.length === balanced.seats.length, `every seat gets a plan, got ${plans.length} of ${balanced.seats.length}`);
  const writers = plans.filter((p) => !p.shared);
  const readers = plans.filter((p) => p.shared);
  ok(writers.length === 1, `exactly one writer gets its own worktree, got ${writers.length}`);
  ok(readers.length === balanced.seats.length - 1, "everyone read-only shares the base checkout");
  ok(writers[0].branch === "vh/rate-limiter/impl", `the branch is namespaced by mission and seat, got ${writers[0].branch}`);
  ok(!writers[0].path.startsWith("/repo/app/"), `the worktree is a SIBLING of the repo, not inside it, got ${writers[0].path}`);
  ok(writers[0].path.startsWith("/repo/app-si-"), `sibling path is ${writers[0].path}`);
  ok(readers.every((r) => r.path === "/repo/app"), "read-only seats point at the real repo, so they review what is actually there");
  ok(/review a tree nobody is writing to/.test(readers[0].reason), "and the reason explains why they are not isolated");
  const argv = writers[0].createArgv[0];
  ok(argv[0] === "worktree" && argv[1] === "add" && argv.includes("-b"), `creation is real git argv: git ${argv.join(" ")}`);
  ok(argv[argv.length - 1] === "main", "and it branches from the base branch");
  ok(setupArgv(planCollaboration(balanced, { ...REPO, objective: "x" }))[0][0] === "git", "setup argv is prefixed with git");
  const td = teardownArgv(planCollaboration(balanced, { ...REPO, objective: "x" }));
  ok(td.some((a) => a.includes("prune")), "teardown prunes, so leftover worktrees do not accumulate");
}
{
  const twoWriters = { ...adversarial, seats: adversarial.seats.map((s) => s.role === "tester" ? { ...s, mayWrite: true } : s) };
  const plans = planWorktrees(twoWriters, REPO);
  ok(plans.filter((p) => !p.shared).length === 2, "two writing seats get two worktrees");
  const branches = plans.filter((p) => !p.shared).map((p) => p.branch);
  ok(new Set(branches).size === 2, `and they are on different branches: ${branches.join(", ")}`);
  const paths = plans.filter((p) => !p.shared).map((p) => p.path);
  ok(new Set(paths).size === 2, "in different directories, so they cannot overwrite each other");
}
{
  const weird = { ...balanced, seats: [{ ...balanced.seats[2], id: "impl/../etc passw\xF8rd!" }] };
  const p = planWorktrees(weird, REPO).find((x) => !x.shared);
  ok(!/[^\w./-]/.test(p.branch.replace("vh/rate-limiter/", "")), `an awkward seat id still yields a legal branch: ${p.branch}`);
  ok(!p.branch.includes(".."), "and path traversal cannot be smuggled into a branch name");
}
console.log("\n== 2. the config bridge ==\n");
{
  const files = writeContextFiles(balanced, { objective: "Add a rate limiter", constraints: ["No new dependencies"], doNotTouch: ["src/legacy/**"] });
  const paths = files.map((f) => f.path);
  ok(paths.includes("AGENTS.md"), `the in-process runtime gets AGENTS.md; got ${paths.join(", ")}`);
  ok(
    paths.filter((p) => p === "AGENTS.md").length === 1,
    "AGENTS.md is written ONCE even though the crew has two seats"
  );
  for (const gone of ["CLAUDE.md", ".clinerules", ".cursor/rules/mj.mdc", ".kilo/rules"]) {
    ok(
      !paths.some((p) => p.includes(gone.split("/")[0])),
      `${gone} is not written \u2014 external agent CLIs are removed, so no vendor briefing file is needed`
    );
  }
  const claude = files.find((f) => f.path === "AGENTS.md");
  ok(claude.contents.includes("Add a rate limiter"), "the briefing carries the objective");
  ok(claude.contents.includes("No new dependencies"), "and the constraints");
  ok(claude.contents.includes("src/legacy/**"), "and what is off limits");
  ok(/OTHER worktrees/.test(claude.contents), "and it tells the agent other agents are working elsewhere");
  ok(/Do not reformat/.test(claude.contents), "and forbids drive-by reformatting, which makes other seats' diffs unreviewable");
  ok(/Generated by VH/.test(claude.contents), "and is marked generated, so nobody hand-edits it");
}
{
  const files = writeContextFiles(audit, { objective: "Audit", constraints: [], doNotTouch: [] });
  ok(files.length > 0, "a read-only team still gets a shared briefing");
  ok(files[0].contents.includes("(none declared)"), "and an empty constraint list is stated, not left blank");
}
console.log("\n== 3. claims \u2014 collisions caught before the work ==\n");
{
  const claims = [
    { seatId: "impl", paths: ["src/api/**"], symbols: ["RateLimiter"], declaredAt: "" },
    { seatId: "infra", paths: ["src/api/middleware.ts"], symbols: ["RateLimiter"], declaredAt: "" },
    { seatId: "docs", paths: ["docs/**"], symbols: [], declaredAt: "" }
  ];
  const conflicts = findClaimConflicts(claims);
  ok(conflicts.length === 1, `one conflict, got ${conflicts.length}`);
  ok(conflicts[0].severity === "symbol", "and it is SYMBOL-level, the dangerous kind");
  ok(conflicts[0].on.includes("RateLimiter"), "naming the function both would rewrite");
  ok(/clean-looking and semantically broken/.test(conflicts[0].advice), "explaining why a clean merge is not enough");
  ok(!conflicts.some((c) => c.a === "docs" || c.b === "docs"), "the docs seat overlaps nothing");
}
{
  const a = [
    { seatId: "x", paths: ["src/**"], symbols: [], declaredAt: "" },
    { seatId: "y", paths: ["src/api/routes.ts"], symbols: [], declaredAt: "" }
  ];
  const c = findClaimConflicts(a);
  ok(c.length === 1 && c[0].severity === "path", "a glob overlapping a concrete path is a conflict");
  ok(findClaimConflicts([{ seatId: "x", paths: ["a/**"], symbols: [], declaredAt: "" }, { seatId: "y", paths: ["b/**"], symbols: [], declaredAt: "" }]).length === 0, "disjoint globs are not a conflict");
  ok(findClaimConflicts([]).length === 0, "no claims, no conflicts");
  ok(findClaimConflicts([{ seatId: "x", paths: ["a"], symbols: [], declaredAt: "" }]).length === 0, "a single claim cannot conflict with itself");
}
console.log("\n== 4. cross-vendor verification ==\n");
{
  const v = planVerification(adversarial);
  ok(v.length === 1, "one writing seat, one verification pair");
  ok(v[0].independent === true, "the adversarial team's verifier IS independent");
  ok(v[0].verifierHarness !== v[0].producerHarness, `${v[0].verifierHarness} checks ${v[0].producerHarness}`);
  ok(/blind spots are not shared/.test(v[0].reason), "and the reason says why that matters");
}
{
  const mono = { ...balanced, seats: balanced.seats.map((s) => ({ ...s, harness: "claude" })) };
  const v = planVerification(mono);
  ok(v.every((x) => !x.independent), "with one vendor, nothing is independent");
  ok(v.some((x) => /WARNING/.test(x.reason)), "and VH says so loudly");
  ok(v.some((x) => /advisory, not as verification/.test(x.reason)), "and refuses to call it verification");
}
{
  const none = { ...balanced, seats: balanced.seats.filter((s) => s.role !== "reviewer" && s.role !== "security") };
  const v = planVerification(none);
  ok(v.length === 1 && v[0].verifierId === "", "a team with no reviewer pairs the writer with nobody");
  ok(/Self-certification is not verification/.test(v[0].reason), "and says self-certification does not count");
}
console.log("\n== the whole plan ==\n");
{
  const plan = planCollaboration(adversarial, {
    ...REPO,
    objective: "Add a rate limiter to the API",
    constraints: ["No new dependencies"],
    claims: [
      { seatId: "impl", paths: ["src/api/**"], symbols: [], declaredAt: "" },
      { seatId: "test", paths: ["tests/**"], symbols: [], declaredAt: "" }
    ]
  });
  ok(plan.waves.length >= 4, `${plan.waves.length} execution waves`);
  const first = plan.waves[0];
  ok(first.seats.length === 1 && adversarial.seats.find((s) => s.id === first.seats[0])?.role === "planner", "planning is the first wave");
  const lastWriters = plan.waves.findIndex((w) => w.seats.includes("impl"));
  const lastTesters = plan.waves.findIndex((w) => w.seats.includes("test"));
  const lastReview = plan.waves.findIndex((w) => w.seats.some((s) => adversarial.seats.find((x) => x.id === s)?.role === "reviewer"));
  ok(lastWriters < lastTesters, `writing (wave ${lastWriters + 1}) comes before testing (wave ${lastTesters + 1})`);
  ok(lastTesters < lastReview, `and testing before review (wave ${lastReview + 1}), so the review sees the tested result`);
  ok(plan.conflicts.length === 0, "these claims do not overlap");
  ok(plan.contextFiles.length > 0, "context files are planned");
  const text = renderPlan(plan);
  ok(/isolation:/.test(text) && /execution waves:/.test(text) && /verification:/.test(text), "the plan renders every section");
  ok(/independent/.test(text), "and labels the verifier independent");
}
{
  const twoWriters = { ...adversarial, seats: [...adversarial.seats, { ...adversarial.seats[1], id: "impl2", harness: "codex" }] };
  const plan = planCollaboration(twoWriters, {
    ...REPO,
    objective: "x",
    claims: [
      { seatId: "impl", paths: ["src/**"], symbols: ["Handler"], declaredAt: "" },
      { seatId: "impl2", paths: ["src/handler.ts"], symbols: ["Handler"], declaredAt: "" }
    ]
  });
  ok(plan.conflicts.length === 1, "the symbol conflict is detected");
  ok(plan.conflicts[0].a === "impl" && plan.conflicts[0].b === "impl2", "between the two writers");
  const w1 = plan.waves.findIndex((w) => w.seats.includes("impl"));
  const w2 = plan.waves.findIndex((w) => w.seats.includes("impl2"));
  ok(w1 !== w2, `the two conflicting writers are in different waves (${w1 + 1} vs ${w2 + 1})`);
  ok(plan.waves[w1].seats.length === 1, "each runs alone");
  ok(plan.waves[w2].seats.length === 1, "so they cannot overwrite each other");
  ok(/looks clean and is semantically wrong/.test(plan.waves[w2].why), `and the wave says why: ${plan.waves[w2].why}`);
  ok(plan.problems.some((p) => /symbol-level/.test(p)), "and the plan flags it before starting");
  ok(plan.waves.every((w) => w.seats.length > 0), "no wave is empty");
  const allSeats = plan.waves.flatMap((w) => w.seats);
  ok(new Set(allSeats).size === allSeats.length, `and no seat is scheduled twice: ${allSeats.join(",")}`);
  ok(allSeats.length === twoWriters.seats.length, `every seat is scheduled exactly once (${allSeats.length} of ${twoWriters.seats.length})`);
  const free = planCollaboration(twoWriters, {
    ...REPO,
    objective: "x",
    claims: [
      { seatId: "impl", paths: ["src/a/**"], symbols: [], declaredAt: "" },
      { seatId: "impl2", paths: ["src/b/**"], symbols: [], declaredAt: "" }
    ]
  });
  ok(free.waves.some((w) => w.seats.includes("impl") && w.seats.includes("impl2")), "with disjoint claims they share one wave");
  ok(free.worktrees.filter((w) => !w.shared).length === 2, "in two separate worktrees");
  ok(free.problems.some((p) => /2 different CLIs will write/.test(p)), "and VH still names the reconciliation cost");
}
{
  const plan = planCollaboration(audit, { ...REPO, objective: "Audit this repo" });
  ok(plan.worktrees.every((w) => w.shared), "a read-only team gets no worktrees at all");
  ok(setupArgv(plan).length === 0, "so there is nothing to set up");
  ok(plan.verification.length === 0, "and nothing writes, so nothing needs verifying");
}
{
  const plan = planCollaboration(balanced, { ...REPO, objective: "x" });
  ok(plan.problems.some((p) => /different CLIs will write/.test(p)) === false, "one writer produces no reconciliation warning");
  const multi = { ...balanced, seats: [...balanced.seats, { ...balanced.seats[2], id: "impl2", harness: "codex" }] };
  const p2 = planCollaboration(multi, { ...REPO, objective: "x", claims: [{ seatId: "impl", paths: ["a/**"], symbols: [], declaredAt: "" }, { seatId: "impl2", paths: ["b/**"], symbols: [], declaredAt: "" }] });
  ok(p2.problems.some((p) => /2 different CLIs will write/.test(p)), "two writing CLIs is called out as a real reconciliation cost");
  ok(p2.worktrees.filter((w) => !w.shared).length === 2, "and both get isolated");
}
console.log("\n== 9. a REPEATED mission gets its own worktree (the collision bug) ==");
{
  const team = balanced;
  const opts = (slug) => ({ repoRoot: "/repo/app", baseBranch: "main", missionSlug: slug, deferReview: true });
  const first = planWorktrees(team, opts("mission-one"));
  const second = planWorktrees(team, opts("mission-two"));
  const writerPath = (plans) => plans.find((p) => !p.shared).path;
  const reviewPath = (plans) => plans.find((p) => p.deferred).path;
  ok(
    "two missions for the same seat get DIFFERENT writer worktrees",
    writerPath(first) !== writerPath(second),
    `${writerPath(first)} vs ${writerPath(second)}`
  );
  ok(
    "\u2026and different review worktrees",
    reviewPath(first) !== reviewPath(second),
    `${reviewPath(first)} vs ${reviewPath(second)}`
  );
  ok(
    "the same mission still gets stable, repeatable paths",
    writerPath(planWorktrees(team, opts("mission-one"))) === writerPath(first)
  );
  ok(
    "the path still names the mission, so an operator can tell them apart",
    writerPath(second).includes("mission-two") && reviewPath(second).includes("mission-two")
  );
  ok(
    "the path is still a sibling of the repo, never inside it",
    writerPath(second).startsWith("/repo/app-si-") && !writerPath(second).startsWith("/repo/app/")
  );
  ok(
    "the BRANCH was always mission-scoped, and still is",
    first.find((p) => !p.shared).branch.startsWith("vh/mission-one/") && second.find((p) => !p.shared).branch.startsWith("vh/mission-two/")
  );
  ok(
    "no path traversal can be smuggled in through the slug either",
    !writerPath(planWorktrees(team, opts("../../etc"))).includes("/../")
  );
}
console.log(`
${pass} passed, ${fail} failed
`);
process.exit(fail ? 1 : 0);
