/**
 * §13.1 AGENTS.md round-trip (V11, VH-11.0-PROPOSAL W4).
 *
 * AGENTS.md — plain Markdown, no schema, read natively by 30+ coding tools and stewarded by
 * the Agentic AI Foundation — is how the rest of the ecosystem gives agents project context.
 * V11 makes VH bilingual:
 *
 *   IN   → `collectAgentsContext(cwd)` reads the repo's AGENTS.md files (root plus nested,
 *          nearest-wins, depth-capped) so mission planning starts from the same ground truth
 *          every other tool uses.
 *   OUT  → `agentsMdForMission(...)` writes one AGENTS.md per mission workspace from the
 *          plan: objective, boundaries, done-when contract, per-task verification. A human
 *          can read and correct it in their editor of choice; every harness gets identical
 *          instructions instead of a prompt assembled in JS.
 *
 * There is no cache: the file is the interface, and files change under agents' feet.
 */

import * as fsSync from "node:fs";
import * as path from "node:path";

export interface AgentsMdDoc {
  /** Where the file was found, relative to the search root. */
  file: string;
  /** The file's own heading text, or the path when untitled. */
  title: string;
  /** Section name → body lines, in file order. */
  sections: Array<{ heading: string | null; lines: string[] }>;
  raw: string;
}

export interface AgentsContext {
  docs: AgentsMdDoc[];
  /** The composed context block VH injects into planning. Empty string when nothing found. */
  composed: string;
}

/** Parse one AGENTS.md into sections. Tolerates any Markdown; asserts nothing. */
export function parseAgentsMd(raw: string, file: string): AgentsMdDoc {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const sections: AgentsMdDoc["sections"] = [];
  let current: { heading: string | null; lines: string[] } = { heading: null, lines: [] };
  for (const line of lines) {
    const h = line.match(/^(#{1,3})\s+(.+)$/);
    if (h) {
      if (current.heading !== null || current.lines.some((l) => l.trim())) sections.push(current);
      current = { heading: h[2].trim(), lines: [] };
    } else {
      current.lines.push(line);
    }
  }
  if (current.heading !== null || current.lines.some((l) => l.trim())) sections.push(current);
  const title = sections.find((s) => s.heading !== null)?.heading ?? path.basename(file);
  return { file, title, sections, raw };
}

/**
 * Collect AGENTS.md ground truth for a workspace.
 *
 * Semantics follow the community convention: the root file gives project-wide context, nested
 * files scope and override it. Depth is capped (default 3) so a huge tree cannot stall
 * planning, and unreadable directories are skipped without error — context is a gift, not a
 * contract.
 */
export function collectAgentsContext(root: string, maxDepth = 3): AgentsContext {
  const docs: AgentsMdDoc[] = [];
  const walk = (dir: string, depth: number, rel: string): void => {
    if (depth > maxDepth) return;
    const file = path.join(dir, "AGENTS.md");
    try {
      if (fsSync.statSync(file).isFile()) {
        docs.push(parseAgentsMd(fsSync.readFileSync(file, "utf8"), rel ? `${rel}/AGENTS.md` : "AGENTS.md"));
      }
    } catch {
      /* no file here — that is the normal case */
    }
    if (depth === maxDepth) return;
    let entries: fsSync.Dirent[];
    try {
      entries = fsSync.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.isDirectory() && !e.name.startsWith(".") && e.name !== "node_modules" && e.name !== "target") {
        walk(path.join(dir, e.name), depth + 1, rel ? `${rel}/${e.name}` : e.name);
      }
    }
  };
  walk(root, 0, "");
  const composed = docs
    .map((d) => `### from ${d.file}\n${d.raw.trim()}`)
    .join("\n\n");
  return { docs, composed };
}

/* ------------------------------------------------------------------ writing */

export interface AgentsMdTaskInput {
  title: string;
  kind: string;
  /** Commands that verify this task, e.g. ["npm test"]. */
  checks: string[];
  harness?: string;
}

export interface AgentsMdMissionInput {
  missionId: string;
  objective: string;
  /** The done-when contract, as a list of testable statements. */
  doneWhen: string[];
  /** §33 boundary — what agents may and may not touch, as plain statements. */
  boundaries: string[];
  tasks: AgentsMdTaskInput[];
}

/**
 * Render the AGENTS.md a mission writes into its workspace.
 *
 * Deliberately boring Markdown: instructions other tools can follow verbatim, provenance in a
 * footer so a human knows where it came from and can delete it freely.
 */
export function agentsMdForMission(m: AgentsMdMissionInput): string {
  const lines: string[] = [];
  lines.push(`# ${m.objective}`);
  lines.push("");
  lines.push("<!-- generated by VH for mission ");
  lines.push(`${m.missionId} --`);
  lines.push("");
  lines.push("## Context");
  lines.push("");
  lines.push(`This workspace is being worked on by VH mission \`${m.missionId}\`.`);
  lines.push("Follow the instructions in this file. They are the contract for every agent in this mission.");
  lines.push("");
  lines.push("## Done when");
  lines.push("");
  for (const d of m.doneWhen) lines.push(`- ${d}`);
  lines.push("");
  lines.push("## Boundaries");
  lines.push("");
  for (const b of m.boundaries) lines.push(`- ${b}`);
  lines.push("");
  lines.push("## Tasks");
  lines.push("");
  for (const t of m.tasks) {
    const via = t.harness ? ` (via ${t.harness})` : "";
    lines.push(`### ${t.title}${via}`);
    lines.push(`- kind: ${t.kind}`);
    if (t.checks.length > 0) {
      lines.push(`- verify with: ${t.checks.map((c) => `\`${c}\``).join(", ")}`);
    }
    lines.push("");
  }
  lines.push("## Ground rules");
  lines.push("");
  lines.push("- Never invent tools, APIs, or secrets. Mark unknowns as unknown.");
  lines.push("- Run the verification commands before claiming a task is done.");
  lines.push("- Leave the workspace in a state where those commands pass.");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("This file is regenerated by VH on plan changes. Edit freely — your edits are read by the next seat that starts.");
  lines.push("");
  return lines.join("\n");
}

/** Write the mission's AGENTS.md into a workspace. Returns the path written. */
export function writeAgentsMd(root: string, m: AgentsMdMissionInput): string {
  const file = path.join(root, "AGENTS.md");
  fsSync.mkdirSync(root, { recursive: true });
  fsSync.writeFileSync(file, agentsMdForMission(m), "utf8");
  return file;
}
